In [138]:
import csv
import pandas as pd
import json
import requests
import numpy as np
import os
import time
import math
from collections import defaultdict
from scipy.stats.mstats import winsorize
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pprint
# PATH = "C:/Udemy/2026-Python-EricBanas/Banas/Section53_Finance/redo/"
PATH = "D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/"

pd.set_option('display.max_colwidth', 500)

# pd.set_option('display.max_colwidth', None)

# # Show all columns instead of truncating them
# pd.set_option('display.max_columns', None)

# # Show all rows instead of truncating them
# pd.set_option('display.max_rows', None)

pd.set_option('display.max_colwidth', None)

HEADERS = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiaGVjdG9yYXdzQHlhaG9vLmNvbSIsInBsYW4iOiJ1bHRyYSIsIm5ld3NmZWVkX2VuYWJsZWQiOnRydWUsIndlYnNvY2tldF9zeW1ib2xzIjo1LCJ3ZWJzb2NrZXRfY29ubmVjdGlvbnMiOjF9.oFmidTENqrcgZK1sN3jpjrs79VSMy_kAwNGD7msrM88',
    }

# do not delete
tickers_to_skip = []
missing_tickers = []


# TODO: add def to get ticker info for country

# My Recommendation

# Your next steps should probably be:

# Finish sector screeners
# Select top stocks per sector
# Build covariance matrix
# Calculate:
    # portfolio return
    # volatility
    # Sharpe ratio
    # Plot efficient frontier
# Compare:
    # equal weight
    # optimized portfolio

# That is a very strong investing research pipeline.

In [16]:
%%html
<style>
    .dataframe {width:100%}
    .dataframe th { font-size: 12px; }
    .dataframe td { font-size: 12px; }
    # .dataframe tr > td:last-child { width:50%; font-size: 12px;   }
</style>

In [17]:
sec_df = pd.read_csv(PATH + 'sector-stocks/stock_sectors.csv')
ener_df = sec_df.loc[sec_df['Sector'] == "energy"]
energy = get_rois_for_stocks(ener_df, '2025-01-01','2026-04-15')
energy = energy.sort_values(by='Ticker')
energy
# test

File for ticker BRN doesn't exist
File for ticker BATL doesn't exist
File for ticker CKX doesn't exist
File for ticker DNN doesn't exist
File for ticker EP doesn't exist
File for ticker UUUU doesn't exist
File for ticker EONR doesn't exist
File for ticker EPM doesn't exist
File for ticker GTE doesn't exist
File for ticker IMO doesn't exist
File for ticker INDO doesn't exist
File for ticker ISOU doesn't exist
File for ticker JAGU doesn't exist
File for ticker MXC doesn't exist
File for ticker NINE doesn't exist
File for ticker OBE doesn't exist
File for ticker PED doesn't exist
File for ticker REPX doesn't exist
File for ticker REI doesn't exist
File for ticker TMDE doesn't exist
File for ticker TOPS doesn't exist
File for ticker TPET doesn't exist
File for ticker UEC doesn't exist
File for ticker URG doesn't exist

    Ticker                       Company classification       ROI
167   ACDC         ProFrac Holding Corp.       upstream -0.249093
62     AEC           Anfield Energy Inc.       upstream  0.249583
37    AESI   Atlas Energy Solutions Inc.   oil_services -0.396844
17      AM  Antero Midstream Corporation      midstream  0.466395
61    AMPY          Amplify Energy Corp.       upstream -0.098361
..     ...                           ...            ...       ...
221    WTI            W&T Offshore, Inc.       upstream  0.663449
180   WTTR  Select Water Solutions, Inc.       upstream  0.126592
7      XOM       Exxon Mobil Corporation     integrated  0.449152
100   XPRO     Expro Group Holdings N.V.       upstream  0.262500
226    YPF       YPF Sociedad AnÃƒÂ³nima       upstream -0.068610

[227 rows x 4 columns]

In [18]:

# def get_has_consecutive_years_positive_fcf2(values, num_of_consec_years = 10):
#     consec_years, score, final_score_reached = 0, 0, False
#     max_score = 0
#     years_counted = 0
    
#     for i in range(len(values)):
#         if values[i] is not None:
#             years_counted += 1            
#             if values[i] > 0:
#                 consec_years += 1
#                 if consec_years == num_of_consec_years:
#                     final_score_reached = True
#                     break
#             else:
#                 score = 0
#                 consec_years = 0
                
#     if final_score_reached == True:
#         return num_of_consec_years > 0, years_counted - num_of_consec_years
        
#     return False, 0

# def get_blue_chip_score_for_consecutive_years(values):
#     weights = np.linspace(len(values), 1, len(values)) / len(values) - 1
#     weights = weights[::-1] 
#     blue_chip_score = 3
#     years = 0
#     result, starting_year = get_has_consecutive_years_positive_fcf2(values, 15)
#     if result == True:    
#         blue_chip_score -= (1 + weights[starting_year])
#         years = 15
#     else:
#         result, starting_year = get_has_consecutive_years_positive_fcf2(values, 10)
#         if result == True:
#             blue_chip_score -= (2 * (1 + weights[starting_year]))
#             years = 10
#         else:
#             result, starting_year = get_has_consecutive_years_positive_fcf2(values, 5)
#             if result == True:
#                 blue_chip_score -= (3 * (1 + weights[starting_year]))
#                 years = 5
#             else:
#                 result, starting_year = get_has_consecutive_years_positive_fcf2(values, 3)
#                 if result == True:
#                     blue_chip_score -= 4 * (1 + weights[starting_year])
#                     years = 3
#                 else:
#                     blue_chip_score -= 5
                    
#     return float(blue_chip_score), years

In [249]:
def has_consecutive_positive_values_N_years(values, required_years):
    consec = 0
    
    for i, value in enumerate(values):
        if value is None:
            continue

        if value > 0:
            consec += 1
            if consec >= required_years:
                start_index = i - required_years + 1
                return True, start_index
        else:
            consec = 0

    return False, 0


def get_blue_chip_score_for_consecutive_years(values):
    if not values:
        return 0.0, 0

    # oldest = 0.0, newest = 1.0
    recency_weights = np.linspace(0.0, 1.0, len(values))
    recency_weights = recency_weights[::-1]

    # years, base_score
    streak_rules = [
        (15, 3.0),
        (10, 2.5),
        (5, 2.0),
        (3, 1.5),
    ]

    for required_years, base_score in streak_rules:
        result, start_index = has_consecutive_positive_values_N_years(values, required_years)
        
        if result:
            recency_bonus = recency_weights[start_index]
            final_score = base_score + recency_bonus
            # print ('required_years:', required_years, 'start_index:', start_index, 'base_score:', base_score, 'recency_bonus:', recency_bonus, 'final_score:', final_score)            
            return float(final_score), required_years

    return 0.0, 0

In [20]:
# test_tickers = ['BP','CNQ','CVE','CVX','COP','E','EQNR','XOM','OXY','SHEL','TTE','TMDE']

In [505]:
def get_formatted_data(sector_df, trace = False):
    # data = {
    #     "AAPL": {
            # "pe": [35, 32, 29],
            # "ev_sales": [12, 10, 8],
            # "revenue_growth": [0.12, 0.15, 0.18],
            # "operating_margin": [0.38, 0.40, 0.42],
            # "rule_of_40": [37, 43, 49],
            # "sector": "Technology"
            # ...
    #     },
    # }
    
    data = None    
    tickers, betas, rois = [], [], []

    revs = []
    
    free_cash_flow_fy_hs = []
    
    fcf_yields = []
    fcf_yields_hs = []
    price_return_1ys = []
    price_return_3ys = []
    countries = []
    net_debt_to_ebitdas = []
    net_debt_to_ebitda_hs = []
    
    dividend_yield_recents = []
    
    dividend_payout_ratio_fys = []
    dividend_payout_ratio_fy_hs = []
    
    enterprise_value_ebitda_ttms = []
    enterprise_value_ebitda_fy_hs = []
    classifications = []
    operating_margin_ttms = []
    operating_margin_fy_hs = []
    return_on_invested_capitals = []
    return_on_invested_capital_fy_hs = []
    
    pe_fy_hs = []
    price_earnings_currents = []

    eps_dilu_ttms, eps_dil_fy_hs, eps_frcst_next_fy = [], [], []

    dil_shrs_outstand_fy_hs = []

    fcf_p_share_ttms = []
    fcf_p_share_fy_hs = []

    ev_to_sales_ttms = []
    ev_to_sales_hs = []
    ev_to_sales_currents = []

    current_ratios = []
    current_ratios_hs = []
    
    interest_coverages = []

    total_revenue_fy_hs = []

    market_caps = []

    share_change_pcts = []
    all_share_changes = []

    dividend_payments = []

    ebitda_margin_ttms = []
    ebitda_margin_fy_hs = []

    net_debt_fy_hs = []
    shareholder_yields = []

    ebitda_fy_hs = []
    
    counter = 0
    
    for ticker in energy['Ticker'].values.tolist():
        
        try:
            
            # if ticker not in test_tickers:
            #     continue

            # if ticker not in ['XOM','CNQ']:
            #     continue
            
            data = get_jsondata_from_file('dividends', ticker)
            # print (0)
            
            if data is None:
                continue
            # print (1)
            
            if data.get('data') is None:
                continue
            
            data = data['data']
            
            # print (2)
            
            if len(data) == 0:
                continue

            return_on_invested_capital = get_single_value(ticker, data, "return_on_invested_capital")        
            return_on_invested_capital_fy_h = get_history_indicator_values(ticker, data, 'return_on_invested_capital_fy_h', 5)
            
            operating_margin_fy_h = get_history_indicator_values(ticker, data, 'operating_margin_fy_h', 99)
            operating_margin_ttm = get_single_value(ticker, data, "operating_margin_ttm") 

            total_revenue_fy_h = get_history_indicator_values(ticker, data, 'total_revenue_fy_h', 6)
            
            pe_fy_history = get_history_indicator_values(ticker, data, 'price_earnings_fy_h', 3)
            price_earnings_current = get_single_value(ticker, data, 'price_earnings_current')

            beta = next((item for item in data if item["id"] == 'beta_5_year'), None) 
            
            net_debt_to_ebitda = get_single_value(ticker, data, "net_debt_to_ebitda_fy")
            
            dividend_yield_recent = get_single_value(ticker, data, "dividend_yield_recent")

            dividend_payout_ratio_fy = get_single_value(ticker, data, "dividend_payout_ratio_fy")
            dividend_payout_ratio_fy_h = get_history_indicator_values(ticker, data, "dividend_payout_ratio_fy_h", 3)

            enterprise_value_ebitda_ttm = get_single_value(ticker, data, "enterprise_value_ebitda_ttm")
            enterprise_value_ebitda_fy_h = get_history_indicator_values(ticker, data, "enterprise_value_ebitda_fy_h", 5)

            enterprise_value_fy_h = get_history_indicator_values(ticker, data, 'enterprise_value_fy_h', 5)

            earnings_per_share_diluted_ttm = get_single_value(ticker, data, "earnings_per_share_diluted_ttm")
            earnings_per_share_diluted_fy_h = get_history_indicator_values(ticker, data, "earnings_per_share_diluted_fy_h", 5)
            earnings_per_share_forecast_next_fy = get_single_value(ticker, data, "earnings_per_share_forecast_next_fy")

            total_debt_fy_h = get_history_indicator_values(ticker, data, "total_debt_fy_h", 5)
            
            cash_n_equivalents_fy_h = get_history_indicator_values(ticker, data, "cash_n_equivalents_fy_h", 5)
            
            ebitda_fy_h = get_history_indicator_values(ticker, data, "ebitda_fy_h", 5)

            dil_shrs_outstand_fy_h = get_history_indicator_values(ticker, data, "diluted_shares_outstanding_fy_h", 5)

            fcf_ttm_value = get_single_value(ticker, data, "free_cash_flow_ttm")            
            fcf_h_5_yrs = get_history_indicator_values(ticker, data, 'free_cash_flow_fy_h', 5)
            free_cash_flow_fy_h = get_history_indicator_values(ticker, data, 'free_cash_flow_fy_h', 99) 
            
            fcf_p_share = get_single_value(ticker, data, "free_cash_flow_per_share_ttm")
            fcf_p_share_fy_h = get_history_indicator_values(ticker, data, "free_cash_flow_per_share_fy_h", 3)

            current_assets = get_single_value(ticker, data, "total_current_assets_fy")
            current_liabilities = get_single_value(ticker, data, "total_current_liabilities_fy")

            current_assets_fy_h = get_history_indicator_values(ticker, data, "total_current_assets_fy_h", 3)
            current_liabilities_fy_h = get_history_indicator_values(ticker, data, "total_current_liabilities_fy_h", 3)

            ebit_fy_h = get_history_indicator_values(ticker, data, "ebit_fy_h", 3)

            ebitda_margin_ttm = get_single_value(ticker, data, "ebitda_margin_ttm")
            ebitda_margin_fy_h = get_history_indicator_values(ticker, data, "ebitda_margin_fy_h", 5)
            
            interest_expense_on_debt_fy_h = get_history_indicator_values(ticker, data, "interest_expense_on_debt_fy_h", 3)
            
            dividend_payment_date_h = get_history_indicator_values(ticker, data, "dividend_payment_date_h", 40)
            dividend_amount_h = get_history_indicator_values(ticker, data, "dividend_amount_h", 40)

            net_debt_fy_h = get_history_indicator_values(ticker, data, "net_debt_fy_h", 3)

            if trace:
                print (ticker)
                
            close = get_close(ticker, False)


            if return_on_invested_capital is None:
                continue
                       
            if close == -1 or operating_margin_fy_h is None or operating_margin_ttm is None:
                continue
            
            if earnings_per_share_diluted_ttm is None:
                continue
                
            if fcf_ttm_value is None or len(fcf_h_5_yrs) < 5:
                continue

            if earnings_per_share_forecast_next_fy is None:
                continue
                
            if fcf_p_share is None or fcf_p_share_fy_h is None:
                continue

            if dividend_yield_recent is None:
                continue

            if enterprise_value_ebitda_ttm is None:
                continue

            if has_acceptable_beta(0, 10, beta) == False or sequence_has_zeros_or_none(total_revenue_fy_h) == True or sequence_has_zeros_or_none(pe_fy_history) == True:
                continue

            if current_assets is None or current_liabilities is None:
                continue

            if enterprise_value_ebitda_ttms is None:
                continue

            if enterprise_value_ebitda_fy_h is None:
                continue

            if ebit_fy_h is None:
                continue
                
            if interest_expense_on_debt_fy_h is None:
                continue

            # if 0 in enterprise_value_fy_h or 0 in convert_none_to_zero_in_list(enterprise_value_fy_h):
            #     print (ticker)
            #     continue

                
            #------------------------
            # process the stock data
            #------------------------

            shares_outstanding = get_stock_info(ticker, "current_total_shares_outstanding", False)                          
            market_cap = shares_outstanding * close
            market_caps.append(market_cap)

            ebitda_fy_hs.append(ebitda_fy_h)
            
            tickers.append(ticker)

            
            if trace:
                print (1)

            countries.append(get_country_from_website_url(get_stock_info(ticker, 'website')))

            if trace:
                print (1.1, earnings_per_share_forecast_next_fy)
                 

            eps_dilu_ttms.append(np.around(earnings_per_share_diluted_ttm, decimals=2))
            eps_dil_fy_hs.append(np.around(earnings_per_share_diluted_fy_h, decimals=2).tolist())
            eps_frcst_next_fy.append(np.around(earnings_per_share_forecast_next_fy, decimals=2))
                
            classifications.append(sector_df[sector_df['Ticker'] == ticker]['classification'].item())
            
            rois.append(sector_df[sector_df['Ticker'] == ticker]['ROI'].item())

            
            if trace:
                print ('1.1.1')

            price_return_1ys.append(get_return_N_years_ago(ticker, 1))
            price_return_3ys.append( get_return_N_years_ago(ticker, 3))

            if trace:
                print (1.2)
            
            dividend_yield_recents.append(round(dividend_yield_recent, 2))


            if dividend_payout_ratio_fy is not None:
                dividend_payout_ratio_fys.append(round(dividend_payout_ratio_fy, 2))
            else:
                dividend_payout_ratio_fys.append(0)
                
            dividend_payout_ratio_fy_hs.append(dividend_payout_ratio_fy_h)

            
            if trace:
                print (2)
            

            return_on_invested_capitals.append(np.around(return_on_invested_capital * 100, decimals=2))

            return_on_invested_capital_fy_h = convert_none_to_zero_in_list(return_on_invested_capital_fy_h)
            return_on_invested_capital_fy_hs.append(np.around(np.array(return_on_invested_capital_fy_h), decimals=2).tolist())

            operating_margin_ttms.append(np.around(operating_margin_ttm, decimals=2))

            operating_margin_fy_h = convert_none_to_zero_in_list(operating_margin_fy_h)
            operating_margin_fy_hs.append(np.around(np.array(operating_margin_fy_h), decimals=2).tolist())

            
            if trace:
                print (2)

            total_revenue_fy_hs.append(total_revenue_fy_h)

            if trace:
                print (2.5)

            
            free_cash_flow_fy_hs.append([x for x in free_cash_flow_fy_h if x is not None])
            
            if trace:
                print (2.6)
            
            #  EV to Sales
            total_debt = get_single_value(ticker, data, "total_debt_fy")
            cash = get_single_value(ticker, data, "cash_n_equivalents_fy")

            if trace:
                print (2.7)
                
            enterprise_value = market_cap + total_debt - cash

            # if ticker in ['XOM','CNQ']:
            #     print ('enterprise_value', enterprise_value)
            #     print ('shares_outstanding',shares_outstanding)


            
            latest_total_revenue = get_stock_info(ticker, 'total_revenue', False)
            ev_to_sales_currents.append(round((enterprise_value / latest_total_revenue), 2)  )

  
            if trace:
                print (2.8)
                

            enterprise_value_fy_h = convert_none_to_zero_in_list(enterprise_value_fy_h)
            enterprise_value_fy_h_series = np.array(enterprise_value_fy_h[-5:])
            total_reveue_fy_h_series = np.array(total_revenue_fy_h[-5:])
            ev_to_sales_hs.append(np.around(enterprise_value_fy_h_series / total_reveue_fy_h_series, decimals=2).tolist())


       
            if trace:
                print (2.9)


            enterprise_value_ebitda_fy_h = remove_nones_from_list(enterprise_value_ebitda_fy_h)
            enterprise_value_ebitda_fy_h = np.around(np.array(enterprise_value_ebitda_fy_h), decimals=2).tolist()
            enterprise_value_ebitda_fy_hs.append(enterprise_value_ebitda_fy_h)
            
            enterprise_value_ebitda_ttms.append(np.around(enterprise_value_ebitda_ttm, decimals=2))
            
            if trace:
                print (3)
                
            pe_fy_hs.append(np.around(np.array(pe_fy_history), decimals=2).tolist())
            price_earnings_currents.append(price_earnings_current)

            
            net_debt_to_ebitdas.append(np.around(net_debt_to_ebitda, decimals=2))

            if trace:
                print (4)
    
            
            net_debt_ebitda_numerator = np.array(total_debt_fy_h)  - np.array(cash_n_equivalents_fy_h)
            net_debt_ebitda_denominator = np.array(ebitda_fy_h)
            
            net_debt_to_ebitda_hs.append(np.around(net_debt_ebitda_numerator/net_debt_ebitda_denominator, decimals=2).tolist())

            if trace:
                print (5)
            

            fcf_yield = np.around((fcf_ttm_value / market_cap) * 100, decimals=2)
            fcf_yields.append(fcf_yield)

            
            fcf_yields_no_numpy = []
            for x in range(len(enterprise_value_fy_h)):                
                if enterprise_value_fy_h[x] > 0:
                    fcf_yield = round((fcf_h_5_yrs[x] / enterprise_value_fy_h[x]) * 100, 2)
                else:
                    fcf_yield = 0
                fcf_yields_no_numpy.append(fcf_yield)          

            fcf_yields_hs.append(fcf_yields_no_numpy)
            # fcf_yields_hs.append(np.around((np.array(fcf_h_5_yrs) / np.array(enterprise_value_fy_h) ) * 100, decimals=2).tolist())
            

            if trace:
                print (6)


                
            dil_shrs_outstand_fy_h = [x for x in dil_shrs_outstand_fy_h if x != 0]
            
            #  share dilution
            oldest = dil_shrs_outstand_fy_h[0]
            latest = dil_shrs_outstand_fy_h[-1]
            
            years = len(dil_shrs_outstand_fy_h) - 1
            annualized_share_change = (
                (latest / oldest) ** (1 / years)
            ) - 1

            if ticker == 'EQNR':
                print ('share outstaing oldest:', oldest)
                print ('share outstaing latest:', latest)
                print ('years annualized', years)

                   
            share_change_pcts.append(annualized_share_change)

            if trace:
                print (7)
                
            share_changes = []
            
            for i in range(1, len(dil_shrs_outstand_fy_h)):
                if dil_shrs_outstand_fy_h[i-1] != 0:
                    pct_change = (dil_shrs_outstand_fy_h[i] - dil_shrs_outstand_fy_h[i-1]) / dil_shrs_outstand_fy_h[i-1]
                    share_changes.append(pct_change)

            all_share_changes.append(share_changes)


            if trace:
                print (8)

            
            dil_shrs_outstand_fy_hs.append(np.around(np.array(dil_shrs_outstand_fy_h), decimals=2).tolist())
            # share_buyback_fy_ratios.append(share_buyback_fy_ratio)

            
            fcf_p_share_ttms.append(round(fcf_p_share, 2))
            fcf_p_share_fy_hs.append(np.around(np.array(fcf_p_share_fy_h), decimals=2).tolist())


            if trace:
                print (9)

            
            current_ratio = current_assets / current_liabilities
            current_ratios.append(round(current_ratio, 2))

            cr = np.array(current_assets_fy_h) / np.array(current_liabilities_fy_h)
            current_ratios_hs.append(np.around(cr, decimals=2))

            if trace:
                print (10)

            ebit_fy_h = np.array(ebit_fy_h)
            interest_expense_on_debt_fy_h = np.abs(np.array(interest_expense_on_debt_fy_h))
            interest_coverage = np.around((ebit_fy_h / interest_expense_on_debt_fy_h), decimals=2)

            if trace:
                print (10.1)
                
            def get_min_or_100(x):
                return min(x, 100)
            
            vfunc = np.vectorize(get_min_or_100)
            interest_coverage = vfunc(interest_coverage)
            
            interest_coverages.append(interest_coverage.tolist())

            if trace:
                print (10.2)

            dividends = []
            for i in range(min(len(dividend_payment_date_h), len(dividend_amount_h))):
                if dividend_payment_date_h[i] is not None:
                    dividends.append( { 'date': datetime.fromtimestamp(dividend_payment_date_h[i]).strftime("%Y-%m-%d"),  'amount': dividend_amount_h[i] } )

            if trace:
                print (10.3)
                
            dividend_payments.append(dividends)

            if trace:
                print (10.4)
                
            ebitda_margin_ttms.append(ebitda_margin_ttm)
            ebitda_margin_fy_hs.append(np.around(np.array(ebitda_margin_fy_h), decimals=2).tolist())

            
            if trace:
                print (11)

            net_debt_fy_hs.append(net_debt_fy_h)


                
            dividend_yield_recent = dividend_yield_recents[-1]
            
            if len(net_debt_fy_h) >= 2:
                debt_change_pct = (
                    (net_debt_fy_h[-2] - net_debt_fy_h[-1])
                    / abs(net_debt_fy_h[-2])
                ) * 100
                
                buyback_ratio = annualized_share_change * 100 * -1

               
                if buyback_ratio is not None:

                    debt_paydown_yield = max(debt_change_pct, 0) * 0.02
                    
                    shareholder_yield = dividend_yield_recent + buyback_ratio + (debt_paydown_yield * 0.02)
                    shareholder_yields.append(shareholder_yield)

                    if ticker == 'EQNR':
                        print ('buyback_ratio',buyback_ratio)
                        print ('dividend_yield_recent',dividend_yield_recent)
                        print ('debt_change_pct', debt_change_pct)
                        print ('debt_change_pct * 2%', (debt_change_pct * 0.02))
                        print ('shareholder_yield',shareholder_yield)


                        


           
            # 1. market value per share
            # mv_per_share = market_cap / shares_outstanding

            
            # 2. get earnings per share
            # got it above


        except Exception as e:
            print (f'Error 2 ticker: {ticker} {e}')

    # print (len(ebitda_margin_ttms))
    # print (len(return_on_invested_capitals), len(return_on_invested_capital_fy_hs), len(current_ratios), len(current_ratios_hs), len(fcf_p_share_ttms), len(interest_coverages), len(all_share_changes), len(share_change_pcts))
    # print (len(free_cash_flow_fy_hs),len(total_revenue_fy_hs), len(enterprise_value_ebitda_ttms), len(enterprise_value_ebitda_fy_hs), len(operating_margin_ttms), len(operating_margin_fy_hs), len(ev_to_sales_currents))
    # print (len(pe_fy_hs), len(price_earnings_currents), len(fcf_yields), len(fcf_yields_hs), len(price_return_1ys), len(dividend_yield_recents), len(net_debt_to_ebitdas), len(net_debt_to_ebitda_hs), len(dividend_payout_ratio_fys))
    # print (len(eps_dilu_ttms),len(eps_dil_fy_hs), len(eps_frcst_next_fy), len(fcf_p_share_fy_hs), len(market_caps))
    
    df_2 = pd.DataFrame({
        'ticker': tickers, 
        # 'country': countries,
        'classification': classifications,
        "roic": return_on_invested_capitals,
        "roic_fy_h": return_on_invested_capital_fy_hs,        
        "current_ratio": current_ratios,
        "current_ratio_h": current_ratios_hs,        
        "fcf_p_share_ttm": fcf_p_share_ttms,    
        "fcf_p_share_fy_h": fcf_p_share_fy_hs,
        "interest_coverage": interest_coverages,
        "buyback_share_changes_last_5yrs": all_share_changes,
        "buyback_latest_share_change_pct": share_change_pcts,
        "fcf_fy_h": free_cash_flow_fy_hs,
        'total_revenue_fy_h': total_revenue_fy_hs,
        "ev_ebitda_ttm": enterprise_value_ebitda_ttms,
        "ev_ebitda": enterprise_value_ebitda_fy_hs,
        'operating_margin_ttm': operating_margin_ttms,
        "operating_margin_fy_h": operating_margin_fy_hs,
        "ev_to_sales_current": ev_to_sales_currents,
        "ev_to_sales_hs": ev_to_sales_hs,
        "pe_fy_h": pe_fy_hs,
        "pe_current": price_earnings_currents,
        'fcf_yield': fcf_yields,
        "fcf_yields_fy_h": fcf_yields_hs,
        'price_return_1y': price_return_1ys,
        "price_return_3y": price_return_3ys,
        "dividend_yield_recent": dividend_yield_recents,        
        'net_debt_to_ebitda': net_debt_to_ebitdas,
        "net_debt_to_ebitda_h": net_debt_to_ebitda_hs,
        "dividend_payout_ratio_fy": dividend_payout_ratio_fys,
        "dividend_payout_ratio_fy_h": dividend_payout_ratio_fy_hs,        
        "eps_dilu_ttms": eps_dilu_ttms,
        "eps_dil_fy_hs": eps_dil_fy_hs,
        "eps_frcst_next_fy": eps_frcst_next_fy,
        "market_cap" : market_caps,
        # "dividend_payments": dividend_payments,
        "dil_shares_outst": dil_shrs_outstand_fy_hs,        
        "ebitda_margin_ttm": ebitda_margin_ttms,
        "ebitda_margin_fy_h": ebitda_margin_fy_hs,
        "net_debt_fy_h": net_debt_fy_hs,
        "shareholder_yield": shareholder_yields,
        "ebitda_fy_h": ebitda_fy_hs
    })

    # "buyback_ratio": share_buyback_fy_ratios,

    
    df_2.set_index('ticker', inplace=True)
    dict_2 = df_2.to_dict(orient='index')
    # df_2.to_json(PATH + 'technology.json')

    return df_2, dict_2

In [506]:
df_3, dict_3 = get_formatted_data(energy, False)
df_3

share outstaing oldest: 3254000000
share outstaing latest: 2601000000
years annualized 4
buyback_ratio 5.445826915196983
dividend_yield_recent 2.97
debt_change_pct -34.22479890775074
debt_change_pct * 2% -0.6844959781550147
shareholder_yield 8.415826915196984

,classification,roic,roic_fy_h,current_ratio,current_ratio_h,fcf_p_share_ttm,fcf_p_share_fy_h,interest_coverage,buyback_share_changes_last_5yrs,buyback_latest_share_change_pct,...,eps_dilu_ttms,eps_dil_fy_hs,eps_frcst_next_fy,market_cap,dil_shares_outst,ebitda_margin_ttm,ebitda_margin_fy_h,net_debt_fy_h,shareholder_yield,ebitda_fy_h
ticker,,,,,,,,,,,,,,,,,,,,,
AM,midstream,7.58,"[6.07, 5.95, 6.81, 7.57, 7.93]",3.41,"[0.95, 1.17, 3.41]",1.68,"[1.23, 1.24, 1.6]","[2.85, 3.19, 3.85]","[0.0011756466056330982, 0.004313970435144701, 0.005960130355824965, -0.006326674868675128]",0.001270,...,0.85,"[0.69, 0.68, 0.77, 0.82, 0.86]",1.10,1.012182e+10,"[479736000, 480300000, 482372000, 485247000, 482177000]",73.949501,"[76.78, 75.11, 74.23, 74.02, 74.45]","[3213150000, 3116958000, 2959595000]",3.935056,"[743919000, 744112000, 825751000, 871082000, 937453000]"
APA,upstream,14.32,"[14.82, 61.96, 40.75, 8.23, 12.97]",0.82,"[1.02, 1.15, 0.82]",4.18,"[2.58, 2.01, 4.96]","[9.46, 7.84, 8.33]","[-0.112, -0.07207207207207207, 0.1423948220064725, 0.0169971671388102]",-0.010842,...,4.29,"[2.59, 11.03, 9.24, 2.28, 3.99]",6.13,1.294408e+10,"[375000000, 333000000, 309000000, 353000000, 359000000]",63.105330,"[53.38, 59.95, 61.94, 60.07, 59.2]","[5382000000, 5792000000, 4294000000]",3.674516,"[4262000000, 6639000000, 5128000000, 5849000000, 5281000000]"
ARLP,upstream,10.88,"[10.7, 30.4, 29.21, 15.9, 13.45]",2.10,"[2.27, 2.2, 2.1]",2.64,"[2.85, 2.93, 3.02]","[15.71, 8.85, 7.65]","[0.0, -0.00011719780127899304, 0.006167872901585585, 0.0033068952179515945]",0.002336,...,1.89,"[1.36, 4.39, 4.81, 2.77, 2.4]",2.23,3.208750e+09,"[127195219, 127195219, 127180312, 127964744, 128387910]",30.587875,"[30.85, 38.74, 36.64, 29.02, 31.2]","[291007000, 349836000, 394162000]",9.416398,"[484268000, 937449000, 940379000, 710705000, 684739000]"
AROC,midstream,8.50,"[1.06, 1.76, 4.22, 5.66, 8.57]",1.54,"[1.4, 1.24, 1.54]",1.40,"[0.07, 0.43, 0.69]","[2.32, 2.97, 3.48]","[0.010406375551603767, 0.006088260217717229, 0.05203312082102317, 0.07428483448806775]",0.035310,...,1.84,"[0.18, 0.28, 0.67, 1.05, 1.83]",1.86,6.374264e+09,"[151830000, 153410000, 154344000, 162375000, 174437000]",56.350145,"[40.89, 37.15, 43.48, 48.97, 56.42]","[1598962000, 2210492000, 2423874000]",-1.170963,"[319557000, 314106000, 430598000, 566821000, 840562000]"
BKR,oil_services,10.79,"[-1.03, -2.79, 9.1, 13.2, 10.78]",1.36,"[1.25, 1.32, 1.36]",2.30,"[1.81, 2.05, 2.55]","[12.22, 17.08, 16.02]","[0.19781553398058252, 0.028368794326241134, -0.013793103448275862, -0.006993006993006993]",0.048008,...,3.14,"[-0.27, -0.61, 1.91, 2.98, 2.6]",2.39,6.269874e+10,"[824000000, 987000000, 1015000000, 1001000000, 994000000]",17.459578,"[13.11, 13.78, 14.61, 16.23, 17.11]","[3101000000, 2048000000, 1746000000]",-3.404949,"[2687000000, 2915000000, 3727000000, 4518000000, 4745000000]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WFRD,upstream,14.58,"[-13.43, 0.89, 14.83, 17.5, 13.74]",2.19,"[1.79, 2.01, 2.19]",6.47,"[8.42, 6.58, 6.2]","[6.7, 6.29, 5.56]","[0.02857142857142857, 0.027777777777777776, 0.012162162162162163, -0.030707610146862484]",0.009159,...,6.40,"[-6.43, 0.36, 5.64, 6.76, 5.94]",5.90,7.635593e+09,"[70000000, 72000000, 74000000, 74900000, 72600000]",20.586426,"[14.98, 18.19, 22.41, 24.25, 20.92]","[997000000, 813000000, 600000000]",0.064569,"[546000000, 788000000, 1151000000, 1337000000, 1029000000]"
WHD,oil_services,6.18,"[11.46, 20.24, 22.7, 18.58, 14.11]",5.81,"[3.17, 4.33, 5.81]",4.41,"[3.73, 3.47, 3.15]","[27.28, 80.0, 57.6]","[0.0030220610456331218, 0.04091069861273039, 0.0057261515227787566, -0.1363949196020772]",-0.024158,...,1.06,"[0.83, 1.8, 2.57, 2.77, 2.41]",2.69,4.861925e+09,"[76107000, 76337000, 79460000, 79915000, 69015000]",27.183486,"[25.48, 30.34, 31.38, 32.43, 31.41]","[-93819000, -301127000, -456833000]",3.336435,"[111735000, 208872000, 344261000, 366369000, 338937000]"
WMB,midstream,7.01,"[4.56, 6.14, 9.43, 6.08, 6.75]",0.53,"[0.77, 0.5, 0.53]",0.59,"[2.76, 1.88, 0.73]","[2.49, 2.43, 2.78]","[0.0036586316865249565, 3.5168876035437144e-05, 0.00019546664594774743, 0.0016729983302724387]",0.001390,...,2.28,"[1.24, 1.67, 2.6, 1.82, 2.13]",2.36,9.095438e+10,"[1218215000, 1222672000, 1222715000, 1222954000, 1225000000]",57.359486,"[42.0, 47.45, 53.63, 53.72, 56.05]","[24460000000, 27019000000, 29481000000]",2.541049,"[4440000000, 5387000000, 5337000000, 5777000000, 6631000000]"
WTTR,upstream,1.89,"[-6.5, 6.55, 9.08, 3.56, 2.1]",1.57,"[2.15, 1.65, 1.57]",-0.84,"[1.45, 0.6, -0.77]","[16.81, 9.59, 1.69]","[0.09983575338531274, 0.07684767700574356, -0.011327440556242989, 0.015553437347004099]",0.044262,...,0.20,"[-0.48, 0.5, 0.72, 0.3, 0.21]",0.56,2.623131e+09,"[87275467, 95988679, 103365186, 102194323, 103783796]",16.723568,"[4.8, 12.1, 13.56, 15.41, 15.56]","[-3538000, 113115000, 336440000]",-2.976168,"[36693000, 167917000, 214927000, 223717000, 219046000]"
XOM,integrated,8.68,"[10.86, 24.46, 14.8, 12.2, 9.55]",1.15,"[1.48, 1.31, 1.15]",4.47,"[8.26, 7.15, 5.48]","[21.69, 17.74, 15.88]","[-0.016374269005847954, -0.03638525564803805, 0.06071076011846002, 0.0016286644951140066]",0.001750,...,5.93,"[5.39, 13.26, 8.89, 7.84, 6.7]",10.51,6.130377e+11,"[4275000000, 4205000000, 4052000000, 4298000000, 4305000000]",18.167519,"[17.25, 22.35, 19.19, 18.76, 18.5]","[16141000000, 25122000000, 39806000000]",2.485021,"[48396000000, 89517000000, 64037000000, 63752000000, 59931000000]"

In [510]:
def evaluate_energy_stocks(tickers, data, metrics):
    
    def normalize(score, max_score):
        if max_score <= 0:
            return 0.0
        # If your scoring system allows negative penalties, 
        # map them correctly so penalties aren't instantly wiped to 0.0
        return round(max(min(score / max_score, 1.0), -1.0), 2)
        
    def percentile_rank(values, x):
        values = sorted(v for v in values if v is not None)
        if not values:
            return None
        return sum(v <= x for v in values) / len(values)

    def trend_slope(values):

        if values is None or len(values) < 3:
            return None

        try:
            x = np.arange(len(values))
            slope = np.polyfit(x, values, 1)[0]
            return slope

        except:
            return None
            
    
    def improving(values, threshold=0.05):
    
        slope = trend_slope(values)
    
        if slope is None:
            return False
    
        return (
            slope > threshold and
            values[-1] > values[0]
        )
    
    def deteriorating(values, threshold=-0.05):
    
        slope = trend_slope(values)
    
        if slope is None:
            return False
    
        return slope < threshold
    
    def score_percentile(percentile, max_score=4):
        score = 0
        text = None
        percentile = round(percentile, 2)
        if percentile >= 0.90:
            text = f" ({percentile}) Great "
        elif percentile >= 0.75:
            text = f" ({percentile} )Attra. "
        elif percentile >= 0.50:
            text = f" ({percentile}) Good "
        elif percentile >= 0.30:
            text = f" ({percentile}) Fair "
        elif percentile < 0.10:
            text = f" ({percentile}) Poor "
        else:
            text = f" ({percentile}) Neutral "

        score = ((percentile * 2) - 1) * max_score
        score = max(min(score, max_score), max_score * -1)
        return score, text

        
    def trend_improving(values, higher_is_better=True):
        try:
            if not values or len(values) < 2:
                return False
    
            if higher_is_better:
                return values[-1] > values[0]
            else:
                return values[-1] < values[0]
        except:
            print (f'Error in trend_improving values: {values}')
            return None


    def weighted_slope(values):

        if values is None or len(values) < 3:
            return None
    
        try:
            y = np.array(values, dtype=float)
    
            # x-axis
            x = np.arange(len(y))
    
            # Increasing weights toward recent data
            weights = np.arange(1, len(y) + 1)
    
            slope = np.polyfit(x, y, 1, w=weights)[0]
            return slope
        except:
            return None

        
    def count_pos(ticker, values):
        try:
            return sum([1 for x in values if x > 0])
        except Exception:
            print (f' Error in count_pos {ticker}')

    
    

    UPSTREAM_WEIGHTS = {
        "valuation": 0.10,
        "profitability": 0.16,
        "quality": 0.13,
        "fcf_yield": 0.20,
        "trend": 0.05,
        "growth": 0.03,
        "net_debt_to_ebitda": 0.06,
        "dividend_yield_recent": 0.005,
        "dividend_payout": 0.005,
        "ev_to_ebitda": 0.10,
        "stability": 0.03,
        "compounder": 0.04,
        "blue_chip": 0.02,
        "commodity_resilience": 0.05
    }

    MIDSTREAM_WEIGHTS = {
        "valuation": 0.07,
        "profitability": 0.12,
        "fcf_yield": 0.15,
        "trend": 0.02,
        "growth": 0.01,
        "net_debt_to_ebitda": 0.11,
        "dividend_yield_recent": 0.09,
        "dividend_payout": 0.03,
        "ev_to_ebitda": 0.08,
        "quality": 0.19,
        "stability": 0.10,
        "compounder": 0.10,
        "blue_chip": 0.02,
        "commodity_resilience": 0.01
    }
        
    REFINING_WEIGHTS = {
        "valuation": 0.11,
        "profitability": 0.18,
        "fcf_yield": 0.21,
        "trend": 0.03,
        "growth": 0.02,
        "net_debt_to_ebitda": 0.07,
        "dividend_yield_recent": 0.03,
        "dividend_payout": 0.02,
        "ev_to_ebitda": 0.10,
        "quality": 0.12,
        "stability": 0.05,
        "compounder": 0.04,
        "blue_chip": 0.01,
        "commodity_resilience": 0.03
    }
    
    OIL_SERVICES_WEIGHTS = {
        "valuation": 0.08,
        "profitability": 0.14,
        "fcf_yield": 0.17,
        "trend": 0.04,
        "growth": 0.07,
        "net_debt_to_ebitda": 0.06,
        "dividend_yield_recent": 0.02,
        "dividend_payout": 0.02,
        "ev_to_ebitda": 0.09,
        "quality": 0.15,
        "stability": 0.05,
        "compounder": 0.04,
        "blue_chip": 0.02,
        "commodity_resilience": 0.06
    }

    INTEGRATED_WEIGHTS = {
        "valuation": 0.08,
        "profitability": 0.14,
        "quality": 0.18,
        "growth": 0.01,
        "trend": 0.02,
        "stability": 0.06,
        "fcf_yield": 0.19,
        "net_debt_to_ebitda": 0.08,
        "dividend_yield_recent": 0.015,
        "dividend_payout": 0.014,
        "ev_to_ebitda": 0.08,
        "compounder": 0.08,
        "blue_chip": 0.04,
        "commodity_resilience": 0.05
    }
    
    DEFAULT_ENERGY_WEIGHTS = {
        "valuation": 0.11,
        "profitability": 0.14,
        "fcf_yield": 0.17,
        "trend": 0.06,
        "growth": 0.05,
        "net_debt_to_ebitda": 0.06,
        "dividend_yield_recent": 0.015,
        "dividend_payout": 0.015,
        "ev_to_ebitda": 0.06,
        "quality": 0.14,
        "stability": 0.04,
        "compounder": 0.06,
        "blue_chip": 0.045,
        "commodity_resilience": 0.03
        
    }

    LOW_RISK_COUNTRIES = ["US", "NO", "CA"]
    HIGH_RISK_COUNTRIES = ["KZ", "CN", "RS", "BR"]
    MIN_UNIVERSE_SIZE = 5

    results = {}
    metric_universes = defaultdict(lambda: defaultdict(list))

    all_roic_values = [data[t]["roic"] for t in tickers if data[t].get("roic") is not None]
    all_current_ratios = [data[t]["current_ratio"] for t in tickers if data[t].get("current_ratio") is not None]
    all_fcf_p_share_ttm = [data[t]["fcf_p_share_ttm"] for t in tickers if data[t].get("fcf_p_share_ttm") is not None]
    all_interest_coverage = [data[t]["interest_coverage"][-1] for t in tickers if data[t].get("interest_coverage") is not None]
    all_shares_changes_pct = [data[t]["buyback_latest_share_change_pct"] for t in tickers if data[t].get("buyback_latest_share_change_pct") is not None]
        
    fcf_fy_h = [(t, data[t]["fcf_fy_h"]) for t in tickers if data[t].get("fcf_fy_h") is not None]
    all_pos_fcf_years = [count_pos(row[0], row[1]) for row in fcf_fy_h]
    
    all_growth_values = [get_growth_rates(data[t].get("total_revenue_fy_h", []))[-1] for t in tickers if get_growth_rates(data[t].get("total_revenue_fy_h", []))]
    all_ev_to_ebitda =  [data[t]["ev_ebitda_ttm"] for t in tickers if data[t].get("ev_ebitda_ttm") is not None]    
    all_operating_margin_values = [data[t]["operating_margin_ttm"] for t in tickers if data[t].get("operating_margin_ttm") is not None]
    all_ev_sales = [data[t]["ev_to_sales_current"] for t in tickers if data[t].get("ev_to_sales_current") is not None]
    all_pe_currents =  [data[t]["pe_current"] for t in tickers if data[t].get("pe_current") is not None]
    all_fcf_yields = [data[t]["fcf_yield"] for t in tickers if data[t].get("fcf_yield") is not None]    
    all_dividend_yields =  [data[t]["dividend_yield_recent"] for t in tickers if data[t].get("dividend_yield_recent") is not None]
    all_dividend_payout_ratios = [data[t]["dividend_payout_ratio_fy"] for t in tickers if data[t].get("dividend_payout_ratio_fy") is not None]
    all_net_debt_ebitda = [data[t]["net_debt_to_ebitda"] for t in tickers if data[t].get("net_debt_to_ebitda") is not None]
    all_ebitda_margin_ttm = [data[t]["ebitda_margin_ttm"] for t in tickers if data[t].get("ebitda_margin_ttm") is not None]
    
    all_shareholder_yields = [data[t]["shareholder_yield"] for t in tickers if data[t].get("shareholder_yield") is not None]
    
    # create universes of metrics for percentile comparison
    #  -------------------------------------------------------------------
    
    for ticker in tickers:   
        d = data.get(ticker, {})
        classification = d.get("classification")
        
        if not classification or classification is None:
            raise Exception("Missing classification")

        roic = d.get("roic")
        if roic is not None:
            metric_universes[classification]["roic"].append(roic)
        
        fcf_yield = d.get("fcf_yield")
        if fcf_yield is not None:
            metric_universes[classification]["fcf_yield"].append(fcf_yield)

        op_margin = d.get("operating_margin_ttm")
        if op_margin is not None:
            metric_universes[classification]["op_margin"].append(op_margin)

        debt = d.get("net_debt_to_ebitda")
        if debt is not None:
            metric_universes[classification]["net_debt_to_ebitda"].append(debt)

        current_ratio = d.get("current_ratio")
        if current_ratio is not None:
            metric_universes[classification]["current_ratio"].append(current_ratio)
        
        interest_coverage =  d.get('interest_coverage')
        if interest_coverage:
            interest_coverage = interest_coverage[-1]
            metric_universes[classification]["interest_coverage"].append(interest_coverage)
        
        fcf_p_share = d.get('fcf_p_share_ttm')
        if fcf_p_share is not None:
            metric_universes[classification]["fcf_p_share"].append(fcf_p_share)

        buyback_ratio = d.get('buyback_latest_share_change_pct')  
        if buyback_ratio is not None:
            metric_universes[classification]["buyback_ratio"].append(buyback_ratio)

        fcf = d.get("fcf_fy_h")
        if fcf is not None:
            metric_universes[classification]["fcf_pos_years"].append(count_pos(ticker, d.get("fcf_fy_h")))
            metric_universes[classification]["fcf_h"].append(d.get("fcf_fy_h")[-1])
            

        ev_to_sales_current = d.get('ev_to_sales_current')
        if  ev_to_sales_current is not None:
            metric_universes[classification]["ev_to_sales_current"].append(ev_to_sales_current)

        ev_ebitda_ttm = d.get('ev_ebitda_ttm')
        if  ev_ebitda_ttm is not None:
            metric_universes[classification]["ev_ebitda_ttm"].append(ev_ebitda_ttm)

        pe_current = d.get('pe_current')
        if  pe_current is not None:
            metric_universes[classification]["pe_current"].append(pe_current)

        revenues = d.get("total_revenue_fy_h")
        if revenues is not None:
            growths = get_growth_rates(revenues)
            if growths:
                metric_universes[classification]["revenue_growth"].append(growths[-1])

        ebitda_margin_ttm = d.get("ebitda_margin_ttm")
        if ebitda_margin_ttm is not None:
             metric_universes[classification]["ebitda_margin"].append(ebitda_margin_ttm)
    
        dividend_payout_ratio = d.get('dividend_payout_ratio_fy')
        if dividend_payout_ratio is not None:
            metric_universes[classification]["dividend_payout_ratio"].append(dividend_payout_ratio)

        shareholder_yield = d.get('shareholder_yield')
        if shareholder_yield is not None:
            metric_universes[classification]["shareholder_yield"].append(shareholder_yield)
            
    #  -------------------------------------------------------------------
    # Start scoring
    #  -------------------------------------------------------------------
    
    max_bc = 0
    
    for ticker in tickers:
        
        # if ticker not in ['XOM','CNQ']:
        #     continue

        QUALITY_MAX = 0
        TREND_MAX = 0
        GROWTH_MAX = 0
        VALUATION_MAX = 0
        EV_TO_EBITDA_MAX = 0
        PROFITABILITY_MAX = 0
        FCF_YIELD_MAX = 0
        DIVIDEND_YIELD_RECENT_MAX  = 0
        NET_DEBT_TO_EBITDA_MAX = 0
        DIVIDEND_PAYOUT_RATIO_MAX = 0
        BLUE_CHIP_MAX = 0
        STABILITY_MAX = 0
        COMMODITY_RESILIENCE_MAX = 0
        WEIGHTS = DEFAULT_ENERGY_WEIGHTS
        
        final_score = 0
        reasons = []
        valuation_score = 0
        growth_score = 0
        profitability_score = 0
        trend_score = 0
        quality_score = 0
        fcf_yield_score = 0
        net_debt_to_ebitda_score = 0
        dividend_yield_recent_score = 0
        dividend_payout_score = 0
        ev_to_ebitda_score = 0
        blue_chip_score = 0
        stability_score = 0
        commodity_score = 0
        growth, fcf_yield, price_return_1y = None, None, None
        
        d = data.get(ticker, {})

        classification = d.get("classification")

        if not classification or classification is None:
            raise Exception("Something went wrong!")        

        if classification == "upstream":
            WEIGHTS = UPSTREAM_WEIGHTS
        elif classification == "midstream":
            WEIGHTS = MIDSTREAM_WEIGHTS
        elif classification == "refining":
            WEIGHTS = REFINING_WEIGHTS
        elif classification == "oil_services":
            WEIGHTS = OIL_SERVICES_WEIGHTS
        elif classification == "integrated":
            WEIGHTS = INTEGRATED_WEIGHTS
            
        roic_series = d.get("roic_fy_h", [])
        fcf_per_shares_series =  d.get("fcf_p_share_fy_h", [])
        interest_coverage_series = d.get("interest_coverage", [])
        current_ratio_h_series = d.get("current_ratio_h", [])
        buyback_share_changes_last_5yrs_series = d.get("buyback_share_changes_last_5yrs", [])
        ev_ebitda_series = d.get("ev_ebitda", [])
        op_margin_series = d.get("operating_margin_fy_h", [])
        ev_sales_series = d.get("ev_to_sales_hs", [])
        pe_series = d.get("pe_fy_h", [])
        fcf_yield_series = d.get("fcf_yields_fy_h", [])
        net_debt_to_ebitda_series = d.get("net_debt_to_ebitda_h", [])
        dividend_payout_ratio_series = d.get("dividend_payout_ratio_fy_h", [])
        eps_series = d.get("eps_dil_fy_hs", [])
        dil_shares_outst_series = d.get("dil_shares_outst", [])
        ebitda_margin_series = d.get("ebitda_margin_fy_h", [])
        ebitda_series = d.get("ebitda_fy_h", [])

        
        def showbar():
            print ('-------------------------------------------')
            

        def get_percentile_for_metric(metric_value, series_length, min_series_length, all_metrics, metric_universe):
            if series_length >= min_series_length:
                percentile = percentile_rank(metric_universe, metric_value)
            else:
                percentile = percentile_rank(all_metrics, metric_value)
            return percentile

            
        # ---------------------------------------------------------------
        # 1. VALUATION
        
        if metrics.get("ev_to_sales") == True:
            ev_sales = d.get('ev_to_sales_current')

            if ev_sales is not None and ev_sales > 0:
                VALUATION_MAX += 2
                ev_sales_universe = metric_universes[classification]["ev_to_sales_current"]
                percentile = get_percentile_for_metric(ev_sales, len(ev_sales_universe), MIN_UNIVERSE_SIZE, all_ev_sales, ev_sales_universe)        
                adjusted_percentile = 1 - percentile
                score, text = score_percentile(adjusted_percentile, max_score=2)
                valuation_score += score
                reasons.append(f"{text} EV/Sales")

                universe = [x for x in ev_sales_universe if x is not None and not math.isnan(x)]
                if universe:
                    median_ev_to_sales = np.median(universe)
                    if median_ev_to_sales > 0:
                        spread = (
                            ev_sales - median_ev_to_sales
                        ) / median_ev_to_sales
                        if spread <= -.30:
                            valuation_score += 2
                            reasons.append("EV/Sales very far below subsec valuation")
                        elif spread <= -0.20:
                            valuation_score += 1
                            reasons.append("EV/Sale far below subsec valuation")
                        elif spread >= 0.40:
                            valuation_score -= 2
                            reasons.append("EV/Sale very far above subsec valuation")
                        elif spread >= 0.20:
                            valuation_score -= 1
                            reasons.append("EV/Sale far above subsec valuation")

        if metrics.get("pe") == True:
            pe_current = d.get('pe_current')
            if pe_current is not None and pe_current > 0:
                VALUATION_MAX += 5
                pe_universe = metric_universes[classification]["pe_current"]
                percentile = get_percentile_for_metric(pe_current, len(pe_universe), MIN_UNIVERSE_SIZE, all_pe_currents, pe_universe)                    
                adjusted_percentile = 1 - percentile
                score, text = score_percentile(adjusted_percentile, max_score=3)                
                valuation_score += score
                reasons.append(f"{text} P/E")

                universe  = [x for x in pe_universe if not math.isnan(x)]
                median_pe = np.median(universe)
                if median_pe > 0:
                    spread = (
                        pe_current - median_pe
                    ) / median_pe

                    if spread <= -.30:
                        valuation_score += 2
                        reasons.append("Trades very far below subsec valuation")
                    elif spread <= -0.20:
                        valuation_score += 1
                        reasons.append("Trades far below subsec valuation")                
                    elif spread >= 0.40:
                        valuation_score -= 2
                        reasons.append("Trades very far above subsec valuation")
                    elif spread >= 0.20:
                        valuation_score -= 1
                        reasons.append("Trades far above subsec valuation")



        def score_metric(metric_series, current_metric_value, metric_all_universe, classification, metric_name, max_score2, metric_weight, median_weight):
            median = 0
            if metric_series is not None:                    
                median = np.median(metric_series)
            normalized_metric = current_metric_value * metric_weight + median * median_weight
            metric_universe = metric_universes[classification][metric_name]
            percentile = get_percentile_for_metric(normalized_metric, len(metric_universe), MIN_UNIVERSE_SIZE, metric_all_universe, metric_universe)
            score, text = score_percentile(percentile, max_score=max_score2)
            return score, text
            
        # ---------------------------------------------------------------
        # 2. PROFITABILITY

        if metrics.get("op_margin") == True:
            current_op_margin = d.get("operating_margin_ttm")
            
            if current_op_margin is not None and op_margin_series:
                PROFITABILITY_MAX += 4
                score, text = score_metric(op_margin_series[-5:], current_op_margin, all_operating_margin_values, classification, "op_margin", 4, 0.6, 0.4)
                profitability_score += score
                reasons.append(f"{text} Opr Margn")

                COMMODITY_RESILIENCE_MAX += 1
                margin_std = np.std(op_margin_series[-5:])
                if margin_std < 5:
                    commodity_score += 1
                elif margin_std > 15:
                    commodity_score -= 1
                
                
        if metrics.get("ebitda_margin") == True:
            current_ebitda_margin  = d.get("ebitda_margin_ttm")
            
            if current_ebitda_margin is not None and ebitda_margin_series:
                PROFITABILITY_MAX += 3
                score, text = score_metric(ebitda_margin_series, current_ebitda_margin, all_ebitda_margin_ttm, classification, "ebitda_margin", 3, 0.8, 0.2)                
                profitability_score += score
                reasons.append(f"{text} EBITDA Marg")
            
 
        # ---------------------------------------------------------------
        # 3. QUALITY
        
        if metrics.get("roic") == True:            
            current_roic = d.get("roic")
            
            if current_roic is not None and roic_series:
                QUALITY_MAX += 4
                score, text = score_metric(roic_series, current_roic, all_roic_values, classification, "roic", 4, 0.6, 0.4)
                quality_score += score
                reasons.append(f"{text} ROIC")

        
        if metrics.get("interest_coverage") == True:            
            current_interest_coverage = interest_coverage_series[-1] if interest_coverage_series else None
               
            if current_interest_coverage is not None:
                QUALITY_MAX += 4
                score, text = score_metric(interest_coverage_series, current_interest_coverage, all_interest_coverage, classification, "interest_coverage", 4, 1, 0)
                quality_score += score
                reasons.append(f"{text} Interest Coverage")

                
        if metrics.get("current_ratio") == True:
            current_ratio = d.get('current_ratio')
            
            if current_ratio is not None:
                QUALITY_MAX += 4
                score, text = score_metric(None, current_ratio, all_current_ratios, classification, "current_ratio", 4, 1, 0)
                quality_score += score
                reasons.append(f"{text} Current Ratio") 

        
        if metrics.get("fcf_p_share") == True:            
            fcf_p_share = d.get('fcf_p_share_ttm')        
                    
            if fcf_p_share is not None:
                QUALITY_MAX += 4
                score, text = score_metric(None, fcf_p_share, all_fcf_p_share_ttm, classification, "fcf_p_share", 4, 1, 0)
                quality_score += score  
                reasons.append(f"{text} FCF/Share")   
                
        
        if metrics.get("fcf_h") == True:            
            free_cash_flow_fy_h = d.get('fcf_fy_h')

            if free_cash_flow_fy_h is not None:        
                QUALITY_MAX += 6
                score_consec, years_consecutive = get_blue_chip_score_for_consecutive_years(free_cash_flow_fy_h)
                quality_score += score_consec
                reasons.append(f'{years_consecutive} Year Streak Pos. FCF') 
                fcf_pos_years_universe = metric_universes[classification]["fcf_pos_years"]
                fcf_pos_years_count = count_pos(ticker, free_cash_flow_fy_h)
                percentile = get_percentile_for_metric(fcf_pos_years_count, len(fcf_pos_years_universe), MIN_UNIVERSE_SIZE, all_pos_fcf_years, fcf_pos_years_universe)               
                score, text = score_percentile(percentile, max_score=3)     
                quality_score += score    
                reasons.append(f'{text} Pos. Years FCF')       

                if len(free_cash_flow_fy_h) >= 8:
                    COMMODITY_RESILIENCE_MAX += 2
                    positive_years = sum(1 for x in free_cash_flow_fy_h[-8:] if x > 0)
                    if positive_years >= 8:
                        commodity_score += 2
                    elif positive_years >= 5:
                        commodity_score += 1
                    else:
                        commodity_score -= 1
        
        
        if metrics.get("buyback_ratio") == True:
            buyback_ratio = d.get('buyback_latest_share_change_pct')

            if buyback_ratio is not None:
                QUALITY_MAX += 2                
                buyback_universe = metric_universes[classification]["buyback_ratio"]
                percentile = get_percentile_for_metric(buyback_ratio, len(buyback_universe), MIN_UNIVERSE_SIZE, all_shares_changes_pct, buyback_universe)
                percentile = round(percentile, 2)
                adjusted_percentile = round(1 - percentile, 2)
                score, _ = score_percentile(adjusted_percentile, max_score=2)     
                quality_score += score
                
                if score >= 1.5:
                    reasons.append(f"Aggressive ({adjusted_percentile:.2f}) buyback")
                elif score >= 0.5:
                    reasons.append(f"Strong ({adjusted_percentile:.2f}) shr. buyback")
                elif score > -0.5:
                    reasons.append(f"Neutral ({adjusted_percentile:.2f}) shr. buyback")
                else:
                    reasons.append(f"Poor ({adjusted_percentile:.2f}) shr. buyback")


        if metrics.get("shareholder_yield") == True:
            shareholder_yield = d.get("shareholder_yield")

            if shareholder_yield is not None:
                QUALITY_MAX += 4                
                score, text = score_metric(None, shareholder_yield, all_shareholder_yields, classification, "shareholder_yield", 4, 1, 0)
                quality_score += score
                reasons.append(f"{text} Shrholdr Yield")   

            
        # ---------------------------------------------------------------
        # 4. GROWTH
        
        if metrics.get("rev_growth") == True:
            revenues = d.get("total_revenue_fy_h")
            
            if revenues is not None and len(revenues) >= 4:
                GROWTH_MAX += 3
                growth_rates = get_growth_rates(revenues)
                current_growth = growth_rates[-1] if growth_rates else None

                if current_growth is not None:
                    score, text = score_metric(growth_rates, current_growth, all_growth_values, classification, "revenue_growth", 3, 0.6, 0.4)
                    growth_score += score
                    reasons.append(f"{text} revenue growth")
        
        
        # ---------------------------------------------------------------  
        # 5. SPECIFIC SCORING

        if metrics.get("ev_to_ebitda") == True:
            ev_ebitda_ttm = d.get("ev_ebitda_ttm")
            
            if ev_ebitda_ttm is not None:
                EV_TO_EBITDA_MAX += 3
                ev_ebitda_universe = metric_universes[classification]["ev_ebitda_ttm"]
                universe = ev_ebitda_universe if len(ev_ebitda_universe) >= MIN_UNIVERSE_SIZE else all_ev_to_ebitda
                universe = [x for x in universe if not math.isnan(x)]                    
                universe = [min(x, 30) for x in universe if x > 0]
                percentile = percentile_rank(universe, min(ev_ebitda_ttm, 30))
                adjusted_percentile = 1 - percentile
                score, text = score_percentile(adjusted_percentile, max_score=2)
                ev_to_ebitda_score += score
                reasons.append(f"**{text} EV/EBITDA TTM***")

                median_ev_ebitda = np.median(universe)
                if median_ev_ebitda > 0:
                    spread = (
                        ev_ebitda_ttm - median_ev_ebitda
                    ) / median_ev_ebitda
                    
                    if spread <= -0.30:
                        ev_to_ebitda_score += 1
                        reasons.append("EV/EBITDA far below subsector")
                    elif spread <= -0.20:
                        ev_to_ebitda_score += 0.5
                        reasons.append("EV/EBITDA below subsector")
                    elif spread >= 0.40:
                        ev_to_ebitda_score -= 1
                        reasons.append("EV/EBITDA far above subsector")
                    elif spread >= 0.20:
                        ev_to_ebitda_score -= 0.5
                        reasons.append("EV/EBITDA above subsector")
                                                

        
        if metrics.get("fcf_yield") == True:
            current_fcf_yield = d.get("fcf_yield")
           
            if current_fcf_yield is not None and fcf_yield_series:
                FCF_YIELD_MAX += 4
                score, text = score_metric(fcf_yield_series[-5:], current_fcf_yield, all_fcf_yields, classification, "fcf_yield", 4, 0.6, 0.4)
                fcf_yield_score += score
                reasons.append(f"{text} FCF Yield") 
    
                if len(fcf_yield_series) >= 3 and min(fcf_yield_series[-3:]) > 0:
                    FCF_YIELD_MAX += 1
                    fcf_yield_score += 1                

        
        if metrics.get("dy") == True:
            dividend_yield_recent = d.get("dividend_yield_recent")
            
            if dividend_yield_recent is not None:
                DIVIDEND_YIELD_RECENT_MAX += 3                
                if dividend_yield_recent >= 12:  
                    dividend_yield_recent_score -= 2
                    reasons.append("High risk of dividend cut (Yield > 12%)")
                elif dividend_yield_recent >= 9: 
                    dividend_yield_recent_score -= 1 
                    reasons.append("Very high yield; verify coverage ratio")
                elif dividend_yield_recent >= 6: 
                    dividend_yield_recent_score += 3 
                    reasons.append("Excellent Dividend Yield")
                elif dividend_yield_recent >= 4: 
                    dividend_yield_recent_score += 2 
                    reasons.append("Strong Dividend Yield")
                elif dividend_yield_recent >= 2: 
                    dividend_yield_recent_score += 1
                    reasons.append("Fair Dividend Yield")
                else:
                    dividend_yield_recent_score += 0
                    reasons.append("Low Dividend Yield")

                payout_ratio = d.get("dividend_payout_ratio_fy")
                free_cash_flow_fy_h = d.get('fcf_fy_h')
                
                if payout_ratio is not None and free_cash_flow_fy_h is not None:
                    free_cash_flow = free_cash_flow_fy_h[-1]
                    if dividend_yield_recent >= 6 and payout_ratio < 75 and free_cash_flow > 0:
                        DIVIDEND_YIELD_RECENT_MAX += 2
                        dividend_yield_recent_score += 2
                        reasons.append("High yield appears better supported")

                    
        if metrics.get("nd_ebit") == True:
            net_debt_to_ebitda = d.get("net_debt_to_ebitda")        
            
            if net_debt_to_ebitda is not None:
                NET_DEBT_TO_EBITDA_MAX = 4                
                net_debt_to_ebitda_universe = metric_universes[classification]["net_debt_to_ebitda"]
                percentile = get_percentile_for_metric(net_debt_to_ebitda, len(net_debt_to_ebitda_universe), MIN_UNIVERSE_SIZE, all_net_debt_ebitda, net_debt_to_ebitda_universe)
                adjusted_percentile = 1 - percentile
                score, text = score_percentile(adjusted_percentile, max_score=4)
                net_debt_to_ebitda_score += score
                reasons.append(f"{text} Net Debt / EBITDA")    

                COMMODITY_RESILIENCE_MAX += 1
                if net_debt_to_ebitda < 1:
                    commodity_score += 1
                elif net_debt_to_ebitda > 3:
                    commodity_score -= 1

        
        if metrics.get("div_payout") == True:
            dividend_payout_ratio_fy = d.get("dividend_payout_ratio_fy")
            
            if dividend_payout_ratio_fy is not None:
                DIVIDEND_PAYOUT_RATIO_MAX = 1                
                if dividend_payout_ratio_fy < 50:
                    dividend_payout_score += 1
                    reasons.append("Healthy dividend payout")
                elif dividend_payout_ratio_fy <= 75:
                    dividend_payout_score += 0
                    reasons.append("Moderate dividend payout")
                elif dividend_payout_ratio_fy <= 90:
                    dividend_payout_score -= 1
                    reasons.append("Elevated dividend payout")
                elif dividend_payout_ratio_fy > 90:
                    dividend_payout_score -= 2
                    reasons.append("Unsustainable dividend payout")


        
        reasons.append('** TRENDS **')

                    
        # ---------------------------------------------------------------        
        # 6.  TREND SCORING

        if metrics.get("ebitda_margin") == True and len(ebitda_margin_series) >= 3:
            if ebitda_margin_series is not None:
                TREND_MAX += 1
                if deteriorating(ebitda_margin_series, threshold=-0.4):
                    trend_score -= 1
                    reasons.append("EBITDA Marg deter")
                elif improving(ebitda_margin_series, threshold=0.4):
                    trend_score += 1
                    reasons.append("EBITDA Marg improv")

        
        if metrics.get("roic") == True and len(roic_series) >= 3:
            TREND_MAX += 1
            roic_last_3_years = roic_series[-3:]
            if deteriorating(roic_last_3_years, threshold=-0.4):
                trend_score -= 1
                reasons.append("ROIC deter")
            elif improving(roic_last_3_years, threshold=0.4):
                trend_score += 1
                reasons.append("ROIC improv")


        if metrics.get("current_ratio") == True:
            current_ratio_slope = weighted_slope(current_ratio_h_series)
            if current_ratio_slope is not None:
                TREND_MAX += .25                
                if current_ratio_slope > 0:
                    reasons.append("Current Ratio improv")
                    trend_score += 0.25
                elif current_ratio_slope < 0:
                    trend_score -= 0.25
                    reasons.append("Current Ratio deter")
                            

        if metrics.get("interest_coverage") == True and len(interest_coverage_series) >= 3:
            TREND_MAX += 1
            slope = weighted_slope(interest_coverage_series)
            latest_ic = interest_coverage_series[-1] if interest_coverage_series else None
            if improving(interest_coverage_series, threshold=0.25):
                reasons.append("Interest Cov. improving")
                trend_score += 1
            
            elif deteriorating(interest_coverage_series, threshold=-0.40):
            
                # Only penalize if coverage is already weak
                if latest_ic < 4:
                    reasons.append("Interest Cov. deteriorating")
                    trend_score -= 1
                else:
                    reasons.append("Interest Cov. still strong")
            
            else:
                reasons.append("Interest Cov. stable")
    
        
        if metrics.get("fcf_p_share") == True and len(fcf_per_shares_series) >= 3:
            TREND_MAX += 1
            if improving(fcf_per_shares_series, threshold=0.25):
                reasons.append("FCF/Share improving")            
                trend_score += 1        
        
        if metrics.get("buyback_ratio") == True:
            TREND_MAX += 1
            slope = round(weighted_slope(buyback_share_changes_last_5yrs_series), 2) if buyback_share_changes_last_5yrs_series else None
            
            if slope is not None:
                if slope <= -0.02:
                    trend_score += 1
                    reasons.append("Strong share reduction")
                elif slope <= -0.005:
                    trend_score += 0.5
                    reasons.append("Improving share reduction")
                elif slope >= 0.02:
                    trend_score -= 1
                    reasons.append("Aggressive dilution")
                elif slope >= 0.005:
                    trend_score -= 0.5
                    reasons.append("Increasing dilution")
            

        # “Falling knife” penalty
        if metrics.get("pr1yr") == True:
            price_return_1y = d.get("price_return_1y")
            if price_return_1y is not None:
                TREND_MAX += 2                
                if price_return_1y > .40:
                    trend_score += 2
                    reasons.append("Strong 1Y price momentum")
                elif price_return_1y > .15:
                    trend_score += 1
                    reasons.append("Positive 1Y price momentum")
                elif price_return_1y < -.20:
                    trend_score -= 2
                    reasons.append("Weak 1Y price momentum")
                elif price_return_1y < 0:
                    trend_score -= 1
                    reasons.append("Negative 1Y price momentum")


                revenues = d.get("total_revenue_fy_h")
                if revenues is not None and len(revenues) >= 4:
                    growth_rates = get_growth_rates(revenues)
                    current_growth = growth_rates[-1] if growth_rates else None
                    if current_growth is not None:
                        if (price_return_1y < -.25 and current_growth < .10):
                            trend_score -= 2
                            reasons.append("Weak momentum with slow growth")

        # "Cash Cow" Logic
        if metrics.get("fcf_yield") == True and metrics.get("eps") == True:
            current_fcf_yield = d.get("fcf_yield")
            if current_fcf_yield is not None and current_fcf_yield > 7:
                TREND_MAX += 1                
                if not trend_improving(eps_series, True):
                    # Offset the EPS penalty if the cash flow is great
                    trend_score += 1 
                    reasons.append("Strong FCF offsetting EPS cyclicality")

        if metrics.get("op_margin") == True:        
            TREND_MAX += 1
            if improving(op_margin_series[-5:], threshold=.25):
                trend_score += 1
                reasons.append("Operating margin improving")
        
        if metrics.get("fcf_yield") == True:
            TREND_MAX += 1  
            if improving(fcf_yield_series[-3:], threshold=.5):
                trend_score += 1
                reasons.append("FCF Yield rising")
        
        if metrics.get("nd_ebit") == True:
            TREND_MAX += 1
            if trend_improving(net_debt_to_ebitda_series, higher_is_better=False):            
                trend_score += 1
                reasons.append("Net Debt to EBITDA decreasing")

        if metrics.get("div_payout") == True:
            TREND_MAX += 1            
            if trend_improving(dividend_payout_ratio_series, higher_is_better=False):            
                trend_score += 1
                reasons.append("Div. Payout decreasing")

        if metrics.get("ev_to_sales") == True:
            TREND_MAX += 1                
            if deteriorating(ev_sales_series[-3:]):
                trend_score += 1
                reasons.append("EV/Sales decreasing")

        if metrics.get("pe") == True:
            TREND_MAX += 1           
            if deteriorating(pe_series, threshold=-0.25):
                trend_score += 1
                reasons.append("P/E decreasing")

        
        
        def cagr(start, end, years):
            if start <= 0 or end <= 0:
                return None
            return (end / start) ** (1 / years) - 1


        # EV/EBITDA trend with confirmation
        if metrics.get("ev_to_ebitda") == True:
            ev_ebitda_trend = weighted_slope(ev_ebitda_series)           
        
            if ev_ebitda_trend is not None and ev_ebitda_trend < -0.25:
                TREND_MAX += 2                           
                confirmation_count = 0
                price_return = d.get("price_return_1y")

                #  EBITDA growth
                if ebitda_series and len(ebitda_series) >= 3:
                    if min(ebitda_series) <= 0:
                        ebitda_growth = weighted_slope(ebitda_series)
                    else:
                        ebitda_growth = cagr(ebitda_series[0], ebitda_series[-1], len(ebitda_series) - 1)
    
                    # if ebitda is growing but price is falling
                    if ebitda_growth is not None and price_return is not None:
                        # print (ticker, price_return, ebitda_growth)
                        if price_return < 0 and ebitda_growth > abs(price_return):
                            confirmation_count += 1
    
                # revenue growth
                revenues = d.get("total_revenue_fy_h")
                if revenues and len(revenues) >= 4:
                    revenues = revenues[-4:]
                    growth_rates = get_growth_rates(revenues[-4:])
                    if min(growth_rates) < 0:
                        revenue_growth = weighted_slope(growth_rates)                
                    else:
                        revenue_growth = cagr(revenues[0], revenues[-1], len(revenues) - 1)  
                        
                    if revenue_growth is not None and revenue_growth > 0:
                        confirmation_count += 1

                #  FCF growth
                free_cash_flow_fy_h = d.get('fcf_fy_h')
                if free_cash_flow_fy_h and len(free_cash_flow_fy_h) >= 3:
                    fcf_5_years = free_cash_flow_fy_h[-5:]
                    if min(fcf_5_years) < 0: 
                        fcf_growth = weighted_slope(fcf_5_years)
                    else:
                        fcf_growth = cagr(fcf_5_years[0], fcf_5_years[-1], len(fcf_5_years) - 1)
                        
                    if fcf_growth is not None and fcf_growth > 0:
                        confirmation_count += 1

                # ROIC growth
                current_roic = d.get("roic")
                if current_roic is not None and roic_series:
                    roic_universe = metric_universes[classification]["roic"]
                    median_roic = np.median(roic_series)
                    normalized_roic = current_roic * 0.6 + median_roic * 0.4
                    percentile = get_percentile_for_metric(normalized_roic, len(roic_universe), MIN_UNIVERSE_SIZE, all_roic_values, roic_universe)
                    roic_slope = weighted_slope(roic_series)
                    if (roic_slope is not None and roic_slope > 0) or (percentile is not None and percentile > .6):
                        confirmation_count += 1

                # NET Debt/EBITDA 
                if len(net_debt_to_ebitda_series) >= 3:
                    net_debt_to_ebitda_slope = weighted_slope(net_debt_to_ebitda_series[-3:])
                    if net_debt_to_ebitda_slope is not None and net_debt_to_ebitda_slope < 0:
                        confirmation_count += 1
                
                # Op. Margin growth
                if len(op_margin_series) >= 3:
                    op_margin_slope = weighted_slope(op_margin_series[-3:])
                    if op_margin_slope is not None and op_margin_slope > 0:
                        confirmation_count += 1

                # Share outstanding trend
                shares_outstanding_slope = round(weighted_slope(buyback_share_changes_last_5yrs_series), 2) if buyback_share_changes_last_5yrs_series else None
                if shares_outstanding_slope is not None and shares_outstanding_slope <= 0:
                    confirmation_count += 1
                
                if confirmation_count >= 3:
                    trend_score += 2
                    reasons.append("Healthy EV/EBITDA compression")
                else:
                    trend_score += 0
                    reasons.append("EV/EBITDA falling but weak confirmation")
                
        
        
        if metrics.get("eps") == True:
            TREND_MAX += 2
            eps_ttm = d.get("eps_dilu_ttms")
            eps_forecast = d.get("eps_frcst_next_fy")
            eps = eps_series[-1] if eps_series else None
            
            if eps_ttm is not None:
                if eps_ttm > 0:
                    
                    if trend_improving(eps_series, True):
                        trend_score += 1
                        reasons.append("EPS improving")
                    elif eps_ttm > 1.00: # New: "The Blue Chip Buffer"
                        trend_score += 0.5
                        reasons.append("EPS dipping but remains robust per share")
                        
                    if eps is not None and eps_forecast is not None:
                        if eps_forecast > eps * 1.15:
                            trend_score += 1
                            reasons.append("Strong forecasted EPS growth")
                            
                        elif eps_forecast < eps * 0.85:
                            trend_score -= 1
                            reasons.append("Forecasted EPS decline")

        # ---------------------------------------------------------------  
        # 5. BLUE CHIP SCORING
        
        if metrics.get("bc") == True:
            BLUE_CHIP_MAX += 6
            market_cap = d.get("market_cap")
            if market_cap is not None:
                if market_cap > 300_000_000_000:
                    blue_chip_score += 2
                elif market_cap > 100_000_000_000:
                    blue_chip_score += 1
                    
            country = d.get('country')
            if country in LOW_RISK_COUNTRIES:
                blue_chip_score += 1

            dividend_payments = d.get("dividend_payments")
            
            if dividend_payments is not None:

                score = round(dividend_cagr(dividend_payments), 2)
                
                if score is not None:
                    if score >= 8:
                        blue_chip_score += 3
                        reasons.append(f"Excellent div grth {score}")
                    elif score >= 5:
                        blue_chip_score += 2
                        reasons.append(f"Strong div grth {score}")
                    elif score >= 2:
                        blue_chip_score += 1
                        reasons.append(f"Stable div grth {score}")
                    elif score < 0:
                        blue_chip_score -= 2
                        reasons.append(f"Dividend shrinking {score}")

            #  TODO 
            # A better blue-chip model combines:

            # stability
            # credit quality
            # profitability durability
            # drawdown resilience
            # years FCF positive

        
        # ---------------------------------------------------------------        
        # 7.  STABILITY SCORING

        reasons.append('** STABILITY **')

        if metrics.get("stability") == True:
            if metrics.get("roic") == True:
                if len(roic_series) >= 3:
                    STABILITY_MAX += 2
                    ratio, score, reason = score_stability_coeff_var(roic_series, 'ROIC')
                    stability_score += score
                    reasons.append(reason)
    
            if metrics.get("op_margin") == True:
                if len(op_margin_series) >= 3:
                    STABILITY_MAX += 2
                    op_margins_5_yrs = op_margin_series[-5:]
                    ratio, score, reason = score_stability_coeff_var(op_margins_5_yrs, 'Op. Marg')
                    stability_score += score                
                    reasons.append(reason)
    
            if metrics.get("fcf_h") == True:
                free_cash_flow_fy_h = d.get('fcf_fy_h')
                if free_cash_flow_fy_h and len(free_cash_flow_fy_h) >= 3:
                    STABILITY_MAX += 2
                    fcf_5_years = free_cash_flow_fy_h[-5:]
                    ratio, score, reason = score_stability_coeff_var(fcf_5_years, 'FCF')
                    stability_score += score   
                    reasons.append(reason)
    
            if metrics.get("rev_growth") == True:
                revenues = d.get("total_revenue_fy_h")
                if revenues is not None and len(revenues) >= 4:
                    STABILITY_MAX += 2
                    growth_rates = get_growth_rates(revenues)
                    ratio, score, reason = score_stability_coeff_var(growth_rates, 'Growth')
                    stability_score += score   
                    reasons.append(reason)
    
            if metrics.get("eps") == True:
                if eps_series is not None and len(eps_series) >= 3:
                    STABILITY_MAX += 2
                    ratio, score, reason = score_stability_coeff_var(eps_series, 'EPS')
                    stability_score += score   
                    reasons.append(reason)
        
                    if ratio > 0.60:
                        stability_score -= 2
                        reasons.append("High earnings volatility")


        # ---------------------------------------------------------------        
        # 8.  AVOIDANCE REDUCTIONS

        # Persistent dilution        
        if dil_shares_outst_series is not None and len(dil_shares_outst_series) >= 3:
            # slope = weighted_slope(dil_shares_outst_series)
            
            latest = dil_shares_outst_series[-1]
            earlier = dil_shares_outst_series[-2]
            if earlier and earlier > 0:
                change = (latest - earlier) / earlier
                
                if change > 0.15:
                    quality_score -= 1.5
                    reasons.append("High dilution")
                elif change > 0.10:
                    quality_score -= 1
                    reasons.append("Persistent dilution")
                elif change > 0.05:
                    quality_score -= 0.5
                    reasons.append("Moderate dilution")

        #  Negative FCF streaks
        free_cash_flow_fy_h = d.get('fcf_fy_h')
        if free_cash_flow_fy_h and len(free_cash_flow_fy_h) >= 3:
            negative_years = sum(
                1 for x in free_cash_flow_fy_h if x < 0
            )
            if negative_years >= 5:
                quality_score -= 2
                reasons.append("Long negative FCF streak")
            
            elif negative_years >= 3:
                quality_score -= 1
                reasons.append("Moderate negative FCF streak")

        # Heavy debt
        net_debt_to_ebitda = d.get("net_debt_to_ebitda")        
        if net_debt_to_ebitda is not None:
            if net_debt_to_ebitda > 8:
                net_debt_to_ebitda_score -= 2
                reasons.append("Extreme debt")
            
            elif net_debt_to_ebitda > 6:
                net_debt_to_ebitda_score -= 1
                reasons.append("Elevated debt")

        #  Collpasing margins
        if len(op_margin_series) >= 5 and deteriorating(op_margin_series[-5:], threshold=-1):
            trend_score -= 1
            reasons.append("Margins collapsing")


 
        # ---------------------------------------------------------------        
        # 9. COMPOUNDER BONUS
        
        compounder_score = 0
        COMPOUNDER_MAX = 0
        
        if metrics.get("compounder") == True:
            COMPOUNDER_MAX += 5
        
            op_margins_5_yrs = op_margin_series[-5:] if len(op_margin_series) >= 3 else []
            fcf_5_years = free_cash_flow_fy_h[-5:] if free_cash_flow_fy_h and len(free_cash_flow_fy_h) >= 3 else []
        
            margin_slope = weighted_slope(op_margins_5_yrs)
            roic_slope = weighted_slope(roic_series)
            fcf_slope = weighted_slope(fcf_5_years)
            net_d_to_e_slope = weighted_slope(net_debt_to_ebitda_series)
        
            if roic_slope is not None and roic_slope > 0:
                compounder_score += 1
                reasons.append("Compounder: ROIC improving")
        
            if margin_slope is not None and margin_slope > 0:
                compounder_score += 1
                reasons.append("Compounder: margins improving")
        
            if fcf_slope is not None and fcf_slope > 0:
                compounder_score += 1
                reasons.append("Compounder: FCF improving")
        
            if net_d_to_e_slope is not None and net_d_to_e_slope < 0:
                compounder_score += 1
                reasons.append("Compounder: debt improving")
        
            if dil_shares_outst_series and len(dil_shares_outst_series) >= 3:
                first = dil_shares_outst_series[0]
                latest = dil_shares_outst_series[-1]
        
                if first and first > 0:
                    share_change_pct = (latest - first) / first
                    if share_change_pct < -0.05:
                        compounder_score += 1
                        reasons.append("Compounder: share count shrinking")


               # def trend_component(ticker, slope, values, multiplier=10, cap=1):
        #     avg = abs(np.mean(values)) if values else 0
        #     if avg == 0 or slope is None:
        #         return 0
        #     trend = slope / avg
        #     return max(min(trend * multiplier, cap), -cap)


        
        # ---------------------------------------------------------------        
        # 10. EXPECTED RETURN MODELING
        expected_return = 0

        # 1. Shareholder yield
        shareholder_yield = d.get("shareholder_yield") or 0
        
        # 2. Business growth estimate
        # 2.1 Revenue growth
        revenues = d.get("total_revenue_fy_h", [])[-5:]
        revenue_cagr = cagr(revenues[0], revenues[-1], len(revenues) - 1) if len(revenues) >= 2 else None
        revenue_cagr = revenue_cagr * 100 if revenue_cagr is not None else 0
        
        # 2.2 EBITDA growth
        ebitda_growth = 0
        ebitda_5yrs = ebitda_series[-5:]

        if len(ebitda_5yrs) >= 2:
            if min(ebitda_5yrs) > 0:
                ebitda_growth = cagr(ebitda_5yrs[0], ebitda_5yrs[-1], len(ebitda_5yrs) - 1)
            else:
                avg_ebitda = abs(np.mean(ebitda_5yrs))
                ebitda_growth = (weighted_slope(ebitda_5yrs) / avg_ebitda if avg_ebitda > 0 else 0)
       
        ebitda_growth = (ebitda_growth or 0) * 100
        ebitda_growth = max(min(ebitda_growth, 20), -20)
        
        #  2.3 FCF growth
        free_cash_flow_fy_h = d.get("fcf_fy_h", [])
        fcf_5_years = free_cash_flow_fy_h[-5:] if len(free_cash_flow_fy_h) >= 5 else []
        fcf_growth = 0
        
       
        if len(fcf_5_years) >= 2:
            p90 = float(np.percentile(fcf_5_years, 90))
            fcf_smoothed = [min(x, p90) for x in fcf_5_years]

            if min(fcf_smoothed) > 0:
                fcf_growth = cagr(fcf_smoothed[0], fcf_smoothed[-1], len(fcf_smoothed) - 1)
                fcf_growth = (fcf_growth or 0) * 100
            else:
                fcf_slope = weighted_slope(fcf_smoothed)
                avg_fcf = abs(np.mean(fcf_smoothed))
                fcf_growth = ((fcf_slope / avg_fcf) * 100 if avg_fcf > 0 and fcf_slope is not None else 0)
                
            fcf_growth = max(min(fcf_growth, 5), -5)
        
        if classification == 'integrated':
            growth_estimate = (0.4 * ebitda_growth)  + (0.15 * fcf_growth) + (0.45 * revenue_cagr)
        else:
            growth_estimate = (0.6 * ebitda_growth)  + (0.15 * fcf_growth) + (0.25 * revenue_cagr)
            
        # 2.4 Calculate growth estimate
        growth_estimate = max(min(growth_estimate, 10), -10)

 
        # 2.5 Quality Adjustment
        quality_adjustment = 0

        roic = d.get("roic")
        roic_positive_5yrs, _ = has_consecutive_positive_values_N_years(roic_series[-5:], 5)
        if roic > 15 and roic_positive_5yrs and roic_positive_5yrs:
            quality_adjustment += 1
        
        fcf_5_years = d.get('fcf_fy_h')[-5:]
        fcf_10_years = d.get('fcf_fy_h')[-10:]
        
        if fcf_5_years is not None and len(fcf_5_years) >= 5 and fcf_5_years is not None:
            fcf_positive_5yrs, _ = has_consecutive_positive_values_N_years(fcf_5_years, 5)
            fcf_positive_10yrs, _ = has_consecutive_positive_values_N_years(fcf_10_years, 10)
                
            if fcf_10_years:
                quality_adjustment += 1
            elif fcf_5_years:
                quality_adjustment += .5

        if ticker == 'EQNR':
            print ('quality_adjustment 1', quality_adjustment)
            
        op_margin = d.get("op_margin")
        op_margin_universe = metric_universes[classification]["op_margin"]
        if op_margin is not None and op_margin_universe:
            if op_margin > np.median(op_margin_universe):
                quality_adjustment += 1
        
        quality_adjustment += max(min(quality_adjustment, 3), -3)
        
        if ticker == 'EQNR':
                print ('quality_adjustment 2', quality_adjustment)
           
        # 3. Valuation rerating using EV/EBITDA
        annualized_rerating = 0
        ev_ebitda = d.get("ev_ebitda_ttm")

        univrse = metric_universes[classification]["ev_ebitda_ttm"] if len(ev_ebitda_universe) >= MIN_UNIVERSE_SIZE else all_ev_to_ebitda
        universe = [x for x in universe if x is not None and not math.isnan(x)]
        universe = [min(x, 30) for x in universe if x > 0]
        universe = [x for x in universe if 0 < x < 15]
        
        if ev_ebitda is not None and ev_ebitda > 0 and universe:
           
            median_ev_ebitda = np.median(universe)
            fair_multiple = np.percentile(universe, 40)

            target_multiple = min(
                median_ev_ebitda,
                ev_ebitda * 2
            )
            
            full_rerating = (target_multiple / ev_ebitda) - 1
            full_rerating = max(min(full_rerating, 1.0), -0.5)
            
            if classification == 'integrated':
                partial_rerating = full_rerating * 0.2
            else:
                partial_rerating = full_rerating * 0.5

            annualized_rerating = ((1 + partial_rerating) ** (1 / 3) - 1) * 100
            annualized_rerating = max(min(annualized_rerating, 8), -8)
            
     

           
        # 4. Calculate expected return
        expected_return = (
            shareholder_yield +
            growth_estimate +
            annualized_rerating +
            quality_adjustment
        )

        if ticker == 'EQNR':
            showbar()

    
            print(
                ticker,
                shareholder_yield,
                growth_estimate,
                annualized_rerating,
                quality_adjustment,
                expected_return
            )
            # EQNR 8.415826915196984 0.2097876633642879 6.265856918261115 2 16.891471496822387
            # showbar()
            # print("fcf_growth", fcf_growth)
            # print("ebitda_growth", ebitda_growth)
            # print ('growth_estimate', growth_estimate)
            # print ('quality_adjustment', quality_adjustment)
            # print ('target_multiple', target_multiple)
            # print ('median_ev_ebitda', median_ev_ebitda)
            # print ('ev_ebitda',ev_ebitda)
            # print ('full_rerating', full_rerating)
            # print ('partial_rerating', partial_rerating)
            # print ('annualized_rerating', annualized_rerating)

        
        
        normalized_valuation = normalize(valuation_score, VALUATION_MAX) if VALUATION_MAX > 0 else 0
        normalized_growth = normalize(growth_score, GROWTH_MAX) if GROWTH_MAX > 0 else 0
        normalized_profitability = normalize(profitability_score, PROFITABILITY_MAX) if PROFITABILITY_MAX > 0 else 0
        normalized_quality = normalize(quality_score, QUALITY_MAX) if QUALITY_MAX > 0 else 0
        normalized_ev_to_ebitda = normalize(ev_to_ebitda_score, EV_TO_EBITDA_MAX) if EV_TO_EBITDA_MAX > 0 else 0      
        normalized_fcf_yield = normalize(fcf_yield_score, FCF_YIELD_MAX) if FCF_YIELD_MAX > 0 else 0
        normalized_dividend_yield_recent = normalize(dividend_yield_recent_score, DIVIDEND_YIELD_RECENT_MAX) if DIVIDEND_YIELD_RECENT_MAX > 0 else 0
        normalized_net_debt_to_ebitda = normalize(net_debt_to_ebitda_score, NET_DEBT_TO_EBITDA_MAX) if NET_DEBT_TO_EBITDA_MAX > 0 else 0
        normalized_dividend_payout = normalize(dividend_payout_score, DIVIDEND_PAYOUT_RATIO_MAX) if DIVIDEND_PAYOUT_RATIO_MAX > 0 else 0
        normalized_trend = normalize(trend_score, TREND_MAX) if TREND_MAX > 0 else 0
        normalized_blue_chip = normalize(blue_chip_score, BLUE_CHIP_MAX) if BLUE_CHIP_MAX > 0 else 0
        normalized_stability = normalize(stability_score, STABILITY_MAX) if STABILITY_MAX > 0 else 0
        normalized_compounder = normalize(compounder_score, COMPOUNDER_MAX) if COMPOUNDER_MAX > 0 else 0
        normalized_commodity = normalize(commodity_score, COMMODITY_RESILIENCE_MAX) if COMMODITY_RESILIENCE_MAX > 0 else 0
        


        def round_to_zero(value):
            return 0.0 if abs(round(value, 2)) == 0 else round(value, 2)
            
        final_score = (round_to_zero(normalized_quality * WEIGHTS["quality"]) +
                        round_to_zero(normalized_trend * WEIGHTS["trend"]) +
                        round_to_zero(normalized_growth * WEIGHTS["growth"]) +
                        round_to_zero(normalized_profitability * WEIGHTS["profitability"]) +
                        round_to_zero(normalized_valuation * WEIGHTS["valuation"]) +
                        round_to_zero(normalized_ev_to_ebitda * WEIGHTS['ev_to_ebitda']) +
                        round_to_zero(normalized_dividend_yield_recent * WEIGHTS['dividend_yield_recent']) +
                        round_to_zero(normalized_net_debt_to_ebitda * WEIGHTS['net_debt_to_ebitda']) +
                        round_to_zero(normalized_dividend_payout * WEIGHTS['dividend_payout']) + 
                        round_to_zero(normalized_fcf_yield * WEIGHTS['fcf_yield']) +
                        round_to_zero(normalized_blue_chip * WEIGHTS['blue_chip']) +
                        round_to_zero(normalized_stability * WEIGHTS['stability']) +
                        round_to_zero(normalized_compounder * WEIGHTS['compounder']) +
                        round_to_zero(normalized_commodity * WEIGHTS['commodity_resilience']))
        
        final_score = round_to_zero(final_score)

        # Decision Engine
        if final_score >= 0.40:
            rating = "SB"
        elif final_score >= 0.30:
            rating = "BUY"
        elif final_score >= 0.20:
            rating = "HOLD"
        elif final_score >= 0.10:
            rating = "AVOID"
        else:
            rating = "SELL"

        
               
        if ticker in ['EQNR']:
            showbar()
            print (ticker)
            print ('partial_rerating', partial_rerating)
            print ('full_rerating', full_rerating)
            print ('annualized_rerating', annualized_rerating)
            print('quality_adjustment', quality_adjustment)
            print ('shareholder_yield',shareholder_yield)
            print ('growth_estimate',growth_estimate)
            print("revenue_cagr", revenue_cagr)
           
            print("growth_estimate", growth_estimate)
            print("ev_ebitda", ev_ebitda)
            print("median_ev_ebitda", median_ev_ebitda)


            
        # if fcf_growth > 0 and classification == 'integrated':
        #     print (ticker)
        # print (ticker,'----------------------')
        # # print (valuation_score)
        # # print (growth_score)
        # # print (profitability_score)
        # print ('quality', normalize(quality_score, QUALITY_MAX) * WEIGHTS["quality"])
        # print ('valution', normalize(valuation_score, VALUATION_MAX) * WEIGHTS["valuation"])
        # print ('prof', normalize(profitability_score, PROFITABILITY_MAX) * WEIGHTS["profitability"])
        # print ('grow',normalize(normalized_growth, GROWTH_MAX) * WEIGHTS["growth"])        
        # print ('ev_ebitda', normalize(ev_to_ebitda_score, EV_TO_EBITDA_MAX) * WEIGHTS["ev_to_ebitda"])
        # print ('fcf_y', normalize(fcf_yield_score, FCF_YIELD_MAX) * WEIGHTS["fcf_yield"])
        # print ('net_debt_to_ebitda',normalize(net_debt_to_ebitda_score, NET_DEBT_TO_EBITDA_MAX) * WEIGHTS["net_debt_to_ebitda"])
        # print ('dividend_yield_recent',normalize(dividend_yield_recent_score, DIVIDEND_YIELD_RECENT_MAX) * WEIGHTS["dividend_yield_recent"])
        # print ('dividend_payout',normalize(dividend_payout_score, DIVIDEND_PAYOUT_RATIO_MAX) * WEIGHTS["dividend_payout"])
        # print ('trend',normalize(trend_score, TREND_MAX) * WEIGHTS["trend"])
        # print (ticker,'----------------------')
        # showbar()
        # print ('weights', WEIGHTS)
        # print (ticker, 'quality_scorescore', quality_score)
        # print ('Q MAX', QUALITY_MAX)
        # print ('normalize(net_debt_to_ebitda_score, NET_DEBT_TO_EBITDA_MAX)', round_to_zero(normalized_quality * WEIGHTS["quality"]))
        # print ('normalized_quality',normalized_quality)
        # print ('WEIGHT', WEIGHTS["quality"])
        # print ('normalized_quality * WEIGHT', normalized_quality * WEIGHTS["quality"])
        # print ('trend final', (normalized_trend * WEIGHTS["trend"]))
        # print (classification, ebitda_growth)
        
        results[ticker] = {
                "score": final_score,
                "rating": rating,
                "classification": classification,
                "expected_return": round(expected_return, 2),                
                "expected_return_components": {
                    "growth_estimate": round(growth_estimate, 2),
                    "growth_estimate_components": {
                        'ebitda_growth': ebitda_growth, 
                        'fcf_growth': fcf_growth, 
                        'revenue_cagr': revenue_cagr
                    },
                    "shareholder_yield": round(shareholder_yield, 2),
                    "valuation_rerating": round(annualized_rerating, 2),
                 },  
                "reasons": reasons,
                "weighted_compounder": normalized_compounder * WEIGHTS["compounder"]
            }

    return results

In [511]:
# df_3, dict_3 = get_formatted_data(energy, False)
# df_3.sort_values(by=['classification'], ascending=[True], inplace=True)
metrics = { 
            "stability": True,
            "roic": True, "interest_coverage": True,
            "op_margin": True, "fcf_yield": True,
            "nd_ebit": True,  "pr1yr": True, "rev_growth": True,
            "current_ratio": True, "fcf_h": True, "ev_to_ebitda": True,
            "fcf_p_share": True, "buyback_ratio": True, "ebitda_margin":True,
            "ev_to_sales": True, "pe": True, "dy": True, 
            "div_payout": True, "eps": True, "shareholder_yield": True,
            "bc": True, "compounder": True }
results = evaluate_energy_stocks(df_3.index.tolist(), dict_3, metrics)
# pprint.pprint (results['EQNR'])
df_6 = get_results_report(results)
mask = (df_6['class.'] == 'integrated')
last_col = df_6.columns[-1]
# Set a specific width (e.g., 400 pixels) for that column only
df_6.style.set_properties(subset=[df_6.columns[0]], **{'width': '100px'})
df_6.style.set_properties(subset=[last_col], **{'width': '1000px'})
df_6[mask].sort_values(by=['class.','score'], ascending=[True,False])

quality_adjustment 1 1
quality_adjustment 2 2
-------------------------------------------
EQNR 8.415826915196984 0.2097876633642879 6.265856918261115 2 16.891471496822387
-------------------------------------------
EQNR
partial_rerating 0.2
full_rerating 1.0
annualized_rerating 6.265856918261115
quality_adjustment 2
shareholder_yield 8.415826915196984
growth_estimate 0.2097876633642879
revenue_cagr 4.950662549567597
growth_estimate 0.2097876633642879
ev_ebitda 2.92
median_ev_ebitda 7.31

,rating,score,class.,expected_return,reason
ticker,,,,,
EQNR,SB,0.51,integrated,16.89,"[ (0.73) Good EV/Sales, EV/Sales very far below subsec valuation, (0.55) Good P/E, (1.0) Great Opr Margn, (0.73) Good EBITDA Marg, (0.82 )Attra. ROIC, (1.0) Great Interest Coverage, (0.64) Good Current Ratio, (0.09) Poor FCF/Share, 5 Year Streak Pos. FCF, (0.64) Good Pos. Years FCF, Strong (0.73) shr. buyback, (0.73) Good Shrholdr Yield, (0.82 )Attra. revenue growth, ** (0.91) Great EV/EBITDA TTM***, EV/EBITDA far below subsector, (0.82 )Attra. FCF Yield, Fair Dividend Yield, (0.91) Great Net Debt / EBITDA, Moderate dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio deter, Interest Cov. still strong, Strong share reduction, Strong 1Y price momentum, EV/Sales decreasing, EPS dipping but remains robust per share, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, High earnings volatility, Moderate negative FCF streak, Margins collapsing, Compounder: share count shrinking]"
TTE,SB,0.41,integrated,11.42,"[ (0.64) Good EV/Sales, EV/Sale far below subsec valuation, (0.91) Great P/E, Trades very far below subsec valuation, (0.64) Good Opr Margn, (0.36) Fair EBITDA Marg, (0.82 )Attra. ROIC, (0.45) Fair Interest Coverage, (0.27) Neutral Current Ratio, (0.82 )Attra. FCF/Share, 5 Year Streak Pos. FCF, (0.82 )Attra. Pos. Years FCF, Strong (0.64) shr. buyback, (0.82 )Attra. Shrholdr Yield, (0.73) Good revenue growth, ** (0.64) Good EV/EBITDA TTM***, (0.82 )Attra. FCF Yield, Strong Dividend Yield, (0.64) Good Net Debt / EBITDA, Moderate dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio deter, Interest Cov. still strong, Strong 1Y price momentum, Net Debt to EBITDA decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Moderately variable ROIC, Stable Op. Marg, Unstable FCF, Unstable Growth, Stable EPS, Margins collapsing, Compounder: share count shrinking]"
SHEL,BUY,0.33,integrated,12.92,"[ (0.82 )Attra. EV/Sales, EV/Sales very far below subsec valuation, (0.82 )Attra. P/E, Trades very far below subsec valuation, (0.27) Neutral Opr Margn, (0.18) Neutral EBITDA Marg, (0.36) Fair ROIC, (0.27) Neutral Interest Coverage, (0.91) Great Current Ratio, (0.91) Great FCF/Share, 5 Year Streak Pos. FCF, (0.55) Good Pos. Years FCF, Aggressive (0.91) buyback, (0.91) Great Shrholdr Yield, (0.09) Poor revenue growth, ** (0.73) Good EV/EBITDA TTM***, EV/EBITDA below subsector, (0.91) Great FCF Yield, Fair Dividend Yield, (0.55) Good Net Debt / EBITDA, Healthy dividend payout, ** TRENDS **, EBITDA Marg deter, Current Ratio deter, Interest Cov. stable, Positive 1Y price momentum, Net Debt to EBITDA decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Moderately variable FCF, Unstable Growth, Unstable EPS, Moderate negative FCF streak, Compounder: share count shrinking]"
COP,HOLD,0.24,integrated,9.99,"[ (0.18) Neutral EV/Sales, EV/Sale very far above subsec valuation, (0.45) Fair P/E, (0.91) Great Opr Margn, (0.82 )Attra. EBITDA Marg, (0.91) Great ROIC, (0.55) Good Interest Coverage, (0.91) Great Current Ratio, (0.73) Good FCF/Share, 5 Year Streak Pos. FCF, (0.55) Good Pos. Years FCF, Poor (0.27) shr. buyback, (0.36) Fair Shrholdr Yield, (0.91) Great revenue growth, ** (0.45) Fair EV/EBITDA TTM***, (0.45) Fair FCF Yield, Fair Dividend Yield, (0.73) Good Net Debt / EBITDA, Moderate dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio deter, Interest Cov. still strong, Aggressive dilution, Strong 1Y price momentum, Net Debt to EBITDA decreasing, EV/Sales decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Stable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, Moderate dilution, Moderate negative FCF streak, Margins collapsing, Compounder: share count shrinking]"
CNQ,HOLD,0.21,integrated,10.90,"[ (0.0) Poor EV/Sales, EV/Sale very far above subsec valuation, (0.73) Good P/E, Trades far below subsec valuation, (0.91) Great Opr Margn, (0.91) Great EBITDA Marg, (1.0) Great ROIC, (0.64) Good Interest Coverage, (0.18) Neutral Current Ratio, (0.36) Fair FCF/Share, 5 Year Streak Pos. FCF, (0.09) Poor Pos. Years FCF, Neutral (0.45) shr. buyback, (0.55) Good Shrholdr Yield, (1.0) Great revenue growth, ** (0.18) Neutral EV/EBITDA TTM***, EV/EBITDA above subsector, (0.64) Good FCF Yield, Fair Dividend Yield, (0.45) Fair Net Debt / EBITDA, Healthy dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC improv, Current Ratio improv, Interest Cov. still strong, Increasing dilution, Strong 1Y price momentum, Div. Payout decreasing, P/E decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Moderately variable ROIC, Stable Op. Marg, Moderately variable FCF, Unstable Growth, Moderately variable EPS, Long negative FCF streak, Margins collapsing, Compounder: ROIC improving, Compounder: share count shrinking]"
CVE,AVOID,0.12,integrated,4.43,"[ (0.45) Fair EV/Sales, (0.64) Good P/E, (0.27) Neutral Opr Margn, (0.55) Good EBITDA Marg, (0.82 )Attra. ROIC, (0.73) Good Interest Coverage, (1.0) Great Current Ratio, (0.18) Neutral FCF/Share, 5 Year Streak Pos. FCF, (0.55) Good Pos. Years FCF, Poor (0.36) shr. buyback, (0.27) Neutral Shrholdr Yield, (0.36) Fair revenue growth, ** (0.27) Neutral EV/EBITDA TTM***, (0.82 )Attra. FCF Yield, Low Dividend Yield, (0.18) Neutral Net Debt / EBITDA, Healthy dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio improv, Interest Cov. still strong, Increasing dilution, Strong 1Y price momentum, Net Debt to EBITDA decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, Moderate negative FCF streak, Margins collapsing, Compounder: share count shrinking]"
BP,AVOID,0.10,integrated,20.26,"[ (0.91) Great EV/Sales, EV/Sales very far below subsec valuation, (0.09) Poor P/E, Trades very far above subsec valuation, (0.18) Neutral Opr Margn, (0.18) Neutral EBITDA Marg, (0.09) Poor ROIC, (0.18) Neutral Interest Coverage, (0.73) Good Current Ratio, (0.55) Good FCF/Share, 5 Year Streak Pos. FCF, (0.18) Neutral Pos. Years FCF, Strong (0.82) shr. buyback, (1.0) Great Shrholdr Yield, (0.64) Good revenue growth, ** (0.82 )Attra. EV/EBITDA TTM***, EV/EBITDA far below subsector, (0.91) Great FCF Yield, Strong Dividend Yield, (0.27) Neutral Net Debt / EBITDA, Unsustainable dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio improv, Interest Cov. deteriorating, Strong 1Y price momentum, Strong FCF offsetting EPS cyclicality, Net Debt to EBITDA decreasing, EPS dipping but remains robust per share, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Unstable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, High earnings volatility, Long negative FCF streak, Compounder: share count shrinking]"
OXY,SELL,0.03,integrated,-1.24,"[ (0.09) Poor EV/Sales, EV/Sale very far above subsec valuation, (0.0) Poor P/E, Trades very far above subsec valuation, (0.82 )Attra. Opr Margn, (1.0) Great EBITDA Marg, (0.27) Neutral ROIC, (0.09) Poor Interest Coverage, (0.09) Poor Current Ratio, (0.45) Fair FCF/Share, 10 Year Streak Pos. FCF, (1.0) Great Pos. Years FCF, Poor (0.00) shr. buyback, (0.09) Poor Shrholdr Yield, (0.45) Fair revenue growth, ** (0.55) Good EV/EBITDA TTM***, (0.82 )Attra. FCF Yield, Low Dividend Yield, (0.0) Poor Net Debt / EBITDA, Moderate dividend payout, ** TRENDS **, ROIC deter, Current Ratio improv, Interest Cov. deteriorating, Aggressive dilution, Strong 1Y price momentum, Net Debt to EBITDA decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, High earnings volatility, Margins collapsing]"
XOM,SELL,-0.01,integrated,5.09,"[ (0.36) Fair EV/Sales, (0.36) Fair P/E, Trades far above subsec valuation, (0.27) Neutral Opr Margn, (0.18) Neutral EBITDA Marg, (0.82 )Attra. ROIC, (0.91) Great Interest Coverage, (0.45) Fair Current Ratio, (0.64) Good FCF/Share, 10 Year Streak Pos. FCF, (1.0) Great Pos. Years FCF, Poor (0.09) shr. buyback, (0.18) Neutral Shrholdr Yield, (0.55) Good revenue growth, ** (0.0) Poor EV/EBITDA TTM***, EV/EBITDA far above subsector, (0.45) Fair FCF Yield, Fair Dividend Yield, (0.82 )Attra. Net Debt / EBITDA, Moderate dividend payout, ** TRENDS **, ROIC deter, Current Ratio deter, Interest Cov. still strong, Strong 1Y price momentum, Net Debt to EBITDA decreasing, EPS improving, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Stable Op. Marg, Moderately variable FCF, Unstable Growth, Moderately variable EPS]"
CVX,SELL,-0.08,integrated,6.34,"[ (0.27) Neutral EV/Sales, EV/Sale far above subsec valuation, (0.18) Neutral P/E, Trades very far above subsec valuation, (0.27) Neutral Opr Margn, (0.55) Good EBITDA Marg, (0.36) Fair ROIC, (0.82 )Attra. Interest Coverage, (0.45) Fair Current Ratio, (1.0) Great FCF/Share, 5 Year Streak Pos. FCF, (0.55) Good Pos. Years FCF, Poor (0.18) shr. buyback, (0.45) Fair Shrholdr Yield, (0.45) Fair revenue growth, ** (0.09) Poor EV/EBITDA TTM***, EV/EBITDA far above subsector, (0.55) Good FCF Yield, Fair Dividend Yield, (0.36) Fair Net Debt / EBITDA, Unsustainable dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio improv, Interest Cov. still strong, Aggressive dilution, Positive 1Y price momentum, EPS dipping but remains robust per share, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Unstable FCF, Unstable Growth, Unstable EPS, Moderate negative FCF streak, Margins collapsing]"
E,SELL,-0.08,integrated,4.75,"[ (0.55) Good EV/Sales, EV/Sale far below subsec valuation, (0.27) Neutral P/E, Trades very far above subsec valuation, (0.09) Poor Opr Margn, (0.09) Poor EBITDA Marg, (0.27) Neutral ROIC, (0.36) Fair Interest Coverage, (0.55) Good Current Ratio, (0.36) Fair FCF/Share, 5 Year Streak Pos. FCF, (0.82 )Attra. Pos. Years FCF, Neutral (0.55) shr. buyback, (0.64) Good Shrholdr Yield, (0.55) Good revenue growth, ** (0.36) Fair EV/EBITDA TTM***, (0.73) Good FCF Yield, Fair Dividend Yield, (0.09) Poor Net Debt / EBITDA, Unsustainable dividend payout, ** TRENDS **, EBITDA Marg deter, ROIC deter, Current Ratio deter, Interest Cov. still strong, Strong 1Y price momentum, EPS dipping but remains robust per share, Strong forecasted EPS growth, ** STABILITY **, Unstable ROIC, Moderately variable Op. Marg, Moderately variable FCF, Unstable Growth, Unstable EPS, High earnings volatility, Margins collapsing, Compounder: share count shrinking]"

In [4]:

def get_results_report(results):
    
    values = [v for k, v in results.items()]
    keys = [k for k, v in results.items()]
    df_5 = pd.DataFrame({'key': keys, 'value': values})
    
    buys, ratings, rois, scores, reasons, classifications, expected_returns = [], [], [], [], [], [], []
    
    for index, row in df_5.iterrows():
        buys.append(row['key'])        
        ratings.append(row['value']['rating'])
        scores.append(row['value']['score'])
        classifications.append(row['value']['classification'])
        expected_returns.append(row['value']['expected_return'])
        reasons.append(row['value']['reasons'])
        
    
    df_6 = pd.DataFrame({'ticker': buys, 'rating': ratings, 'score': scores, 'class.': classifications})
    df_6 = pd.DataFrame({'ticker': buys, 'rating': ratings, 'score': scores, 'class.': classifications, 'expected_return': expected_returns ,'reason': reasons })
    
    # , 
    df_6.reset_index(inplace=True)
    df_6.set_index(['ticker'], inplace=True)
    df_6.drop(columns=['index'], inplace=True)
    
    betas = pd.DataFrame(get_beta_5_year_for_df(df_6))
    betas.set_index(['ticker'], inplace=True)
    
    for x in df_3.columns:
        
        if x == 'sector' or x == 'country' or x == 'revenue_growth' or x == "classification" or x == "pe_fy_h": 
            continue

        # if x == "roic":
        #     df_6['roic'] = df_3[x]
        # elif x == "current_ratio":
        #     df_6['current_ratio'] = df_3[x]
        # elif x == "fcf_p_share_ttm":
        #     df_6['fcf_p_share_ttm'] = df_3[x]
        # elif x == "interest_coverage":
        #     df_6['interest_coverage'] = df_3[x]
        # elif x == 'net_debt_to_ebitda':
        #     df_6['net_d_to_ebit'] = df_3[x]
        # elif x == 'fcf_pos_years_5y':
        #     df_6['fcf_pos_5y'] = df_3[x]
        # elif x == "operating_margin_ttms":
        #     df_6['om_ttms'] = df_3[x]
        # elif x == "operating_margin_ttm":
        #     df_6['om_fq_h'] = df_3[x]
        # elif x == "om_ttm":
        #     df_6['om_fq_h'] = df_3[x]
        # elif x == "ev_to_sales_current":
        #     df_6['ev_sales_cur'] = df_3[x]
        # elif x == "price_return_1y":
        #     df_6['ret_1yr'] = df_3[x]
        # elif x == "eps_frcst_next_fy":
        #     df_6['eps_frcst_nxt_fy'] = df_3[x]
        # elif x == "net_debt_to_ebitda_hs":
        #     df_6['net_dbt'] = df_3[x]
        # el
        # elif x == "roic":
        #     pass
        # else:
        #     df_6[x] = df_3[x]
            
    # df_6['beta'] = betas['beta']
    
    return df_6

In [5]:
def score_stability_coeff_var(values, label):
    values = [v for v in values if v is not None]

    if len(values) < 3:
        return 0, f"Not enough {label} history"
    
    avg = np.mean(values)
    
    if avg == 0:
        return 0, f"{label} average is zero"
        
    # print ('values',values)
    # print ('avg', avg)
    # print ('std',   np.std(values) )
    
    stability_ratio = np.std(values) / abs(avg)

    if stability_ratio < 0.10:
        return stability_ratio, 2, f"Very stable {label}"
    elif stability_ratio < 0.20:
        return stability_ratio, 1, f"Stable {label}"
    elif stability_ratio < 0.35:
        return stability_ratio, 0, f"Moderately variable {label}"
    else:
        return stability_ratio, -1, f"Unstable {label}" 


def dividend_cagr(dividend_history):

    """
    Example input:
     [ 
        { "date": "2026-01-01", "amount": 1.34 },
        { "date": "2026-04-01", "amount": 1.40 },
     }
    oldest -> newest
    """
        
    yearly_dividends = defaultdict(float)
    
    for payment in dividend_history:
        year = int(payment["date"][:4])
        yearly_dividends[year] += payment["amount"]


    if not yearly_dividends or len(yearly_dividends) < 2:
        return None
    
    dividend_history = list(yearly_dividends.values())
    
    start = dividend_history[0]
    end = dividend_history[-1]

    if start <= 0:
        return None

    years = len(dividend_history) - 1

    cagr = ((end / start) ** (1 / years)) - 1

    return cagr * 100
    
# g = [{'date': '2019-06-03', 'amount': 0.305}, {'date': '2019-09-03', 'amount': 0.305}, {'date': '2019-12-02', 'amount': 0.42}, 
#      {'date': '2020-03-02', 'amount': 0.42}, {'date': '2020-06-01', 'amount': 0.42},
#      {'date': '2020-09-01', 'amount': 0.42}, {'date': '2020-12-01', 'amount': 0.43}, {'date': '2021-03-01', 'amount': 0.43}, {'date': '2021-06-01', 'amount': 0.43}, {'date': '2021-09-01', 'amount': 0.43}, 
#      {'date': '2021-12-01', 'amount': 0.46}, {'date': '2022-01-14', 'amount': 0.2}, {'date': '2022-03-01', 'amount': 0.46}, {'date': '2022-04-14', 'amount': 0.3}, {'date': '2022-06-01', 'amount': 0.46},
#      {'date': '2022-07-15', 'amount': 0.7}, {'date': '2022-09-01', 'amount': 0.46}, {'date': '2022-10-14', 'amount': 1.4}, {'date': '2022-12-01', 'amount': 0.51}, {'date': '2023-01-13', 'amount': 0.7}, 
#      {'date': '2023-03-01', 'amount': 0.51}, {'date': '2023-04-14', 'amount': 0.6}, {'date': '2023-06-01', 'amount': 0.51}, {'date': '2023-07-14', 'amount': 0.6}, {'date': '2023-09-01', 'amount': 0.51}, 
#      {'date': '2023-10-16', 'amount': 0.6}, {'date': '2023-12-01', 'amount': 0.58}, {'date': '2024-03-01', 'amount': 0.58}, {'date': '2024-03-01', 'amount': 0.2}, {'date': '2024-06-03', 'amount': 0.58}, 
#      {'date': '2024-06-03', 'amount': 0.2}, {'date': '2024-09-03', 'amount': 0.58}, {'date': '2024-09-03', 'amount': 0.2}, {'date': '2024-12-02', 'amount': 0.78}, {'date': '2025-03-03', 'amount': 0.78},
#      {'date': '2025-06-02', 'amount': 0.78}, {'date': '2025-09-02', 'amount': 0.78}, 
#      {'date': '2025-12-01', 'amount': 0.84}, {'date': '2026-03-02', 'amount': 0.84}, {'date': '2026-06-01', 'amount': 0.84}]
# dividend_cagr(g)

def sequence_has_zeros_or_none(items):
    items = [0 if x is None else x for x in items]
    return len([x for x in items if x == 0]) > 0 


def get_jsondata_from_file(folder, ticker):
    try:        
        with open(f"{PATH}{folder}/{ticker}.json", 'r') as file:
            data = json.load(file)
            if len(data) == 0:
                return None
    except Exception as e:
        print (f'Error in get_jsondata_from_file opening file for {ticker} {e}')
        return None
    else:
        return data


def has_acceptable_beta(min, max, beta):
    try:
        if beta is None:
            return False
            
        beta = beta['value']
        
        if beta is None:
            return False
    except Exception as e:
        print (f'Error in get_jsondata_from_file opening file for {ticker} {e}')
        return False
    else:
        return beta > 0 or beta < 10
                    
def convert_none_to_zero_in_list(items):
    return [0 if x is None else x for x in items]



def list_has_at_least_one_value(items):    
    x2 = convert_none_to_zero_in_list(items)
    x2 = [x for x in x2 if x != 0]
    return len(x2) >= 1


def remove_nones_from_list(items):
    return [x for x in items if x != 0 and x is not None]
    

def get_history_indicator_values(ticker, data, indicator_id, num_items):
    roic = []
    try:
        roic = next((item for item in data if item["id"] == indicator_id), None) 
        if roic is None:
            return None
        roic = roic['value']
        roic = roic[:num_items]
        roic = roic[::-1]
    except Exception as e:
        print (f'Error in get_history_indicator_values.{ticker} {e}. Indicator: {indicator_id}')
    else:
        return roic
        
    return None

def get_single_value(ticker, data, indicator_id):
    try:
        value = next((item for item in data if item["id"] == indicator_id), None)
    except Exception as e:
        print (f'Error in get_single_value.{ticker} {e}. Indicator: {indicator_id}')
    else:
        return value.get('value') if value is not None else None

In [6]:
def get_stock_info_from_api(ticker):
    url = f'https://api.insightsentry.com/v3/symbols/NYSE%3A{ticker}/info'
    json_data = None
    response = requests.get(url, headers=HEADERS) 
    try:
        if response.status_code == 200:
            json_data = response.json()
        else:
            url = f'https://api.insightsentry.com/v3/symbols/NASDAQ%3A{ticker}/info'
            response = requests.get(url, headers=HEADERS)          
            if response.status_code == 200:
                json_data = response.json()
    except Exception as e:
        print (f'Error in get_stock_info_from_api {ticker}: {e}')        
    else:
        print(f'Retrieved stock info for {ticker}')
        return json_data

def get_stock_info(ticker, key, overwrite = False):
    json_data = None
    result = None
    try:
        if overwrite == True:
            os.remove(f"{PATH}info/{ticker}.json")
            
        if os.path.exists(f"{PATH}info/{ticker}.json"):
            file_path = f'{PATH}info/{ticker}.json'
            with open(f"{PATH}info/{ticker}.json", 'r') as file:
                data = json.load(file)
                result = data.get(key)
        else:
            json_data = get_stock_info_from_api(ticker)
            if json_data is not None:
                with open(f"{PATH}info/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                result = json_data.get(key)
            else:
                print (f'No info returned for {ticker}')
    except Exception as e:
        print (f'Error in get_stock_total_shares_outstanding {ticker}: {e}')
        return None
    else:
        return result

In [7]:
def count_positive_values_from_list(items):
    items = convert_none_to_zero_in_list (items)
    return len([x for x in items if x > 0])
    
def get_country_from_website_url(url):
    www_index = url.find('www')
   
    if www_index != -1:
        return "US"
    else:
        last_index_l = url.rfind('.')
        end = url[last_index_l + 1:].upper()
        if end == 'COM':
            return 'US'
        else:
            return url[last_index_l + 1:].upper()


def repair_sequence(items):

    if items[-1] is None:
        return None
        
    try:
            
        eps_fy_h_2 = []
        
        num_added = False
        
        for i in range(len(items)):
            if items[i] is not None:
                items.append(items[i])
                num_added = True
            else:
                if i != 0:
                    if num_added == True:
                        return None
    
    except Exception as ex:
        print (f'Error repair_sequance {e}')
        return None
        
    return items

    

    
def get_stock_eps(ticker):

    url = f'https://api.insightsentry.com/v3/symbols/NYSE%3A{ticker}/info'
    json_data = None
    response = requests.get(url, headers=HEADERS)
    print (f'Getting stock info for eps from api for ticker {ticker}')
    if response.status_code == 200:
        json_data = response.json()
        if json_data is None:
            return json_data.get("earnings_per_share_basic_ttm")
    else:
        url = f'https://api.insightsentry.com/v3/symbols/NASDAQ%3A{ticker}/info'
        response = requests.get(url, headers=HEADERS)
        if response.status_code == 200:
            json_data = response.json()
            if json_data is not None:
                return json_data.get("earnings_per_share_basic_ttm")

    return None



def get_one_year_ago_price(ticker):
    try:
        
        df = get_df_from_csv(ticker)
        sdate = datetime.now() - relativedelta(years=1)
        
        edate = sdate + relativedelta(days=4)
        
        sdate = str(datetime.strptime(f"{sdate.year}-{sdate.month}-{sdate.day-1}",'%Y-%m-%d').date())
        # print ('get_one_year_ago_price 4')
        
        edate = str(datetime.strptime(f"{edate.year}-{edate.month}-{edate.day-1}",'%Y-%m-%d').date())
        
        # print (1, sdate, edate)
    
        sdate, edate = get_valid_dates(df, sdate, edate)
        
        # print (2, sdate, edate)
        
        d = float(df.loc[sdate:sdate]['close'].item())
        # print ('get_one_year_ago_price 6')
        
    except Exception as e:
        print(f'Exception in get_one_year_ago_price ticker {ticker}. {e}')
    else:
        return d


def get_valid_dates(df, sdate, edate):
    
    try:
        # mask = (df['date'] > sdate) & (df['date'] <= edate) 
        sm_df = df.loc[sdate:edate]
        if not sm_df.empty:
            sm_date = str(sm_df.index.min()).split(' ')[0]
            last_date = str(sm_df.index.max()).split(' ')[0]
            
            date_leading = str(sm_df.index.min()).split(' ')[0] #'-'.join(('0' if len(x) < 2 else '')+x for x in sm_date.split('-'))
            date_ending = str(sm_df.index.max()).split(' ')[0]  #'-'.join(('0' if len(x) < 2 else '')+x for x in last_date.split('-'))
            # print(date_leading, " ", date_ending)
        else:
            
            return None, None
    except Exception:
        print("Errro in get_valid_dates Date Corrupted")
    else:
        return date_leading, date_ending


def get_expected_growth_cagr (ticker, revenues):

    try:
        start_idx = next((i for i, val in enumerate(revenues) if val > 0), None)

        if start_idx is None or start_idx == len(revenues) - 1:
            return 0.0
        
        # CAGR
        years = len(revenues) - 1
        
        cagr = (revenues[-1] / revenues[start_idx]) ** (1 / years) - 1
    except Exception as e:
        print (f'Error in get_expected_growth_cagr {ticker} {revenues}. {e}')
    else:
        return cagr


def get_close_from_api(ticker):
  
    url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NYSE%3A{ticker}&extended=false&dadj=false'
    print (f'Getting closing price from api for ticker {ticker}')
    json_data = None
    close = -1
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        json_data = response.json()
        
        if json_data['data'][0].get('message') == None:
            close = json_data['data'][0].get('prev_close_price')
        else:
            url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NASDAQ%3A{ticker}&extended=false&dadj=false'
            response = requests.get(url, headers=HEADERS)
            if response.status_code == 200:
                json_data = response.json()
                if json_data['data'][0].get('message') == None:
                    close = json_data['data'][0].get('prev_close_price')
                    
    return close, json_data
        

def get_close(ticker, overwrite=False):
    close = -1
    try:

        if overwrite == True:
            os.remove(f"{PATH}quotes/{ticker}.json")
            
        if os.path.exists(f"{PATH}quotes/{ticker}.json"):
            
            file_path = f'{PATH}quotes/{ticker}.json'
            file_time = os.path.getmtime(file_path)
            if (time.time() - file_time) > (5 * 86400):
                
                close, json_data = get_close_from_api(ticker)
                
                if close > -1:
                    with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                        json.dump(json_data, f, indent=4)
            else:
                with open(f"{PATH}quotes/{ticker}.json", 'r') as file:
                    data = json.load(file)
                    close = data['data'][0].get('prev_close_price')
                
        else:
            close, json_data = get_close_from_api(ticker)
            if close > -1:
                with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                    
    except Exception as e:
        print (f'Error in get_close: {e}')

    return close
    

def get_market_cap_from_api(ticker):
    
    url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NYSE%3A{ticker}&extended=false&dadj=false'
    json_data = None
    market_cap = -1
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        json_data = response.json()
        if json_data['data'][0].get('message') == None:
            market_cap = json_data['data'][0].get('market_cap')
        else:
            url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NASDAQ%3A{ticker}&extended=false&dadj=false'
            response = requests.get(url, headers=HEADERS)
            if response.status_code == 200:
                json_data = response.json()
                if json_data['data'][0].get('message') == None:
                    market_cap = json_data['data'][0].get('market_cap')
        return market_cap, json_data

    
def get_market_cap(ticker):
    json_data = None
    market_cap = -1
    try:
        if os.path.exists(f"{PATH}quotes/{ticker}.json"):
            
            file_path = f'{PATH}quotes/{ticker}.json'
            file_time = os.path.getmtime(file_path)
            if (time.time() - file_time) > (5 * 86400):
                
                market_cap, json_data = get_market_cap_from_api(ticker)
                print (f'Getting market from API for {ticker}')
                
                if market_cap > -1:
                    with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                        json.dump(json_data, f, indent=4)
            else:
                with open(f"{PATH}quotes/{ticker}.json", 'r') as file:
                    data = json.load(file)
                    market_cap = data['data'][0].get('market_cap')
                
        else:
            market_cap, json_data = get_market_cap_from_api(ticker)
            if market_cap > -1:
                with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                    
    except Exception as e:
        print (f'Error: {e}')

    return market_cap



    
def get_df_from_csv(ticker):
    
    # Try to get the file and if it doesn't exist issue a warning
    try:

        if ticker not in tickers_to_skip:
            df = pd.read_csv(PATH + 'converted/' + ticker + '.csv')
            # df['date2'] = pd.DatetimeIndex(['date'])
            df = df.set_index(pd.to_datetime(df['date']))
            df.drop(columns=['date'], inplace=True)
            # df = df.loc[S_DATE_STR:E_DATE_STR]
            return df
        else:
            return None
        # df = delete_unnamed_cols(df)
        
    except FileNotFoundError:
        missing_tickers.append(ticker)
        print(f"File for ticker {ticker} doesn't exist")
        return None
        
def get_rois_for_stocks(stock_df, sdate, edate):

    tickers = []
    classifications = []
    rois = []
    company_names = []
    for index, row in stock_df.iterrows():
        df = get_df_from_csv(row['ticker'])
        if df is None:
            pass
        else:
            mask = (df.index > sdate) & (df.index <= edate)
            
            if len(df.loc[mask]) > 0:
                
                sdate2, edate2 = get_valid_dates(df, sdate, edate)
                roi = roi_between_dates(df, sdate2, edate2)
                # if roi > 0:
                rois.append(roi)
                tickers.append(row['ticker'])
                company_names.append(row['company_name'])
                classifications.append(row['classification'])

    return pd.DataFrame({'Ticker' : tickers,  'Company': company_names , 'classification': classifications, 'ROI' : rois})

def roi_between_dates(df, sdate, edate):
    try: 
        start_val = df.loc[sdate,'close'] 
        end_val = df.loc[edate,'close']
        
        sdate, edate = get_valid_dates(df, start_val, end_val)
        
        # print(f"start_val: {start_val}")
        # print(f"end_val: {end_val}")
        
        roi = ((edate - sdate) / sdate)
    except Exception:
        print("Data Corrupted")
    else:
        return roi



def classify_beta(beta):
    if beta is None:
        return "Unknown"
    elif beta < 0.8:
        return "Low Risk"
    elif beta <= 1.2:
        return "Market-like"
    else:
        return "High Risk"

def get_beta(ticker):
    try:
            
        with open(f'{PATH}dividends/{ticker}.json', 'r') as file:
            data = json.load(file)['data']        
            beta = next((item for item in data if item["id"] == 'beta_5_year'), None)['value']        
            return beta
    except Exception as e:
        print (f"Error in get_beta {ticker}")
    return None
    
def get_beta_5_year_for_df(df):
    betas = []
    for index, row in df.iterrows():
        beta = get_beta(index)
        if beta is not None:
            betas.append({'ticker': index, 'beta': round(beta, 2)})
        else:
            print (f'get_beta_5_year_for_df says: No beta for {index}')
    return betas
    
def get_growth_rates(revenues):
    growth_rates = []
    
    for i in range(1, len(revenues)):
        previous = revenues[i - 1]
        current = revenues[i]
        growth = (current - previous) / previous
        growth *= 100
        growth_rates.append( np.around(growth, decimals=3).item())
    
    return growth_rates

In [8]:
def get_N_years_ago_price(ticker, years_ago = 3):
    try:
        df = get_df_from_csv(ticker)
        sdate = datetime.now() - relativedelta(years=years_ago)
        edate = datetime.now()
        sdate = str(datetime.strptime(f"{sdate.year}-{sdate.month}-{sdate.day}",'%Y-%m-%d').date())
        edate = str(datetime.strptime(f"{edate.year}-{edate.month}-{edate.day}",'%Y-%m-%d').date())
        sdate, edate = get_valid_dates(df, sdate, edate)
        d = float(df.loc[sdate:sdate]['close'].item())
    except Exception as e:
        print(f'Exception in get_one_year_ago_price ticker {ticker}. {e}')
    else:
        return d

In [9]:
def roi_between_dates(df, sdate, edate):
    try: 
        start_date, end_date = get_valid_dates(df, sdate, edate)    
        start_val = df.loc[start_date,'close'] 
        end_val = df.loc[end_date,'close']
        roi = ((end_val - start_val) / start_val)
    except Exception as e:
        print(f'Data Corrupted def roi_between_dates {e}')
    else:
        return roi

def get_return_N_years_ago(ticker, years_ago):
        df = get_df_from_csv(ticker)
        sdate = datetime.now() - relativedelta(years=years_ago)
        edate = datetime.now()        
        sdate = str(datetime.strptime(f"{sdate.year}-{sdate.month}-{sdate.day}",'%Y-%m-%d').date())
        edate = str(datetime.strptime(f"{edate.year}-{edate.month}-{edate.day}",'%Y-%m-%d').date())     
        return float(roi_between_dates(df, sdate, edate))