In [208]:
# Provides ways to work with large multidimensional arrays
import numpy as np 
# Allows for further data manipulation and analysis
import pandas as pd
# from pandas_datareader import data as web # Reads stock data 
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

import time
from datetime import datetime, timezone
# import mplfinance as mpf # Matplotlib finance
import os
from os import listdir
from os.path import isfile, join
from pathlib import Path

import requests
import json
import csv

In [487]:
# Define path to files
PATH = "/Users/hialfonso/Banas/Section53_Finance/"
PATH = "D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/Redo/"

# Start date defaults
S_YEAR = 2017
S_MONTH = 1
S_DAY = 3
S_DATE_STR = f"{S_YEAR}-0{S_MONTH}-0{S_DAY}"
S_DATE_DATETIME = datetime(S_YEAR, S_MONTH, S_DAY)

# End date defaults
E_YEAR = 2021
E_MONTH = 8
E_DAY = 19
E_DATE_STR = f"{E_YEAR}-0{E_MONTH}-{E_DAY}"
E_DATE_DATETIME = datetime(E_YEAR, E_MONTH, E_DAY)

missing_tickers = []

## Get data from endpoint

In [477]:
def save_stock_to_json(exchange, ticker):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiaGVjdG9yYXdzQHlhaG9vLmNvbSIsInBsYW4iOiJwcm8iLCJuZXdzZmVlZF9lbmFibGVkIjp0cnVlLCJ3ZWJzb2NrZXRfc3ltYm9scyI6Miwid2Vic29ja2V0X2Nvbm5lY3Rpb25zIjoxfQ.eXXJXl0mETrgv_aITIsjl_tmT3HQ-RdsiRCw-54NWlw',
    }
    params = {
        'bar_type': 'hour',
        'bar_interval': '1',
        'start_date': '2020-04',
        'dadj': 'false',
        'abbr': 'false',
    }
    
    url = f"https://api.insightsentry.com/v3/symbols/{exchange}%3A{ticker}/series?bar_type=1d&bar_interval=1&dadj=true&dp=3000&long_poll=false&abbr=false"
    
    response = requests.get(url, params=params, headers=headers)
    print (response.status_code)
    if response.status_code == 200:
        data = response.json()
        with open(f"{PATH}/downloaded/{ticker}.json", "w") as f:
            json.dump(data, f, indent=4)
            time.sleep(5)
        
        return True, response.status_code
    
    return False, response.status_code

def download_tickers(num_to_download):
    
    df_next = get_next_tickers_to_download(num_to_download)
    # df_next = pd.DataFrame( ["GNRC", "CPRT", "ODFL", "AMD", "PAYC", "CHTR", "MKC", 
    #              "PG", "PGR", "NEM", "CCI", "COG"], columns=['ticker'])
    # saved, status_code = save_stock_to_json('FRED', 'SP500')
    df_next = pd.DataFrame( ['AAL', 'AME', 'BA', 'CHRW', 'CARR',
       'CAT', 'CTAS', 'CPRT', 'CSX', 'CMI', 'DE', 'DAL', 'DOV', 'ETN',
       'EMR', 'EFX', 'EXPD', 'FAST', 'FDX', 'FTV', 'FBHS', 'GNRC', 'GD',
       'GE', 'HON', 'HWM', 'HII', 'IEX', 'INFO', 'ITW', 'IR', 'JBHT', 'J',
       'JCI', 'KSU', 'LHX', 'LDOS', 'LMT', 'MAS', 'NLSN', 'NSC', 'NOC',
       'ODFL', 'OTIS', 'PCAR', 'PH', 'PNR', 'PWR', 'RTX', 'RSG', 'RHI',
       'ROK', 'ROL', 'ROP', 'SNA', 'LUV', 'SWK', 'TDY', 'TXT', 'TT',
       'TDG', 'UNP', 'UAL', 'UPS', 'URI', 'VRSK', 'GWW', 'WAB', 'WM',
       'XYL'], columns=['ticker'])
    # faang_list = ["META", "AMZN", "AAPL", "NFLX", "GOOG"]
    # df_next = pd.DataFrame(faang_list, columns=['ticker'])


    for index in range(len(df_next)):
        
        ticker = df_next.iloc[index]['ticker']
                
        if not os.path.exists(f"{PATH}downloaded/{ticker}.json"):
            
            saved, status_code = save_stock_to_json('NASDAQ', ticker)
            
            if not saved:
                print (f'Error getting stock data for {ticker} on NASDAQ. Status Code {status_code}. Trying NYSE...')
                
                saved, status_code = save_stock_to_json('NYSE', ticker)
                
                if not saved:
                    print (f'Error getting stock data for {ticker} on NYSE. Status Code {status_code}')
                    with open(f"{PATH}/downloaded/{ticker}.json", "w") as f:
                        json.dump("not found", f, indent=4)
                else: 
                    print ('stock data for ' + ticker + ' saved.')
            else:
                print ('stock data for ' + ticker + ' saved.')
    
        else:
            print (f"File for {ticker} already exists!")
    
    print ('DONE DOWNLOADING!')

def get_downloaded_tickers():
    files = [x for x in listdir(PATH + '/downloaded') if isfile(join(PATH + '/downloaded', x))]
    downloaded_tickers = [os.path.splitext(x)[0] for x in files]
    return downloaded_tickers
    
def get_next_tickers_to_download(num_to_dl):
    df_wil = get_wilshire_tickers()
    df_wil = df_wil.rename(columns={'ticker' : 'ticker1'})
    tickers = get_downloaded_tickers()
    df_dltickers = pd.DataFrame(np.array(tickers), columns=['ticker2'])
    
    result = pd.merge(df_wil, df_dltickers, left_on='ticker1', right_on='ticker2', how='left', suffixes=('_left', '_right'))
    result = result[result['ticker2'].isna()].sort_values(by='ticker1').head(num_to_dl)
    result = result.drop(columns=['ticker2']).rename(columns={'ticker1':'ticker'})
    return result

def get_tickers_not_converted():
        
    files = [x for x in listdir(PATH + '/downloaded') if isfile(join(PATH + '/downloaded', x)) and os.path.getsize(f'{PATH}/downloaded/{x}') > 11]
    df_downloaded_tickers = pd.DataFrame([os.path.splitext(x)[0] for x in files], columns=['ticker1'])
    
    files = [x for x in listdir(PATH + '/converted') if isfile(join(PATH + '/converted', x))]
    df_converted_tickers = pd.DataFrame( [os.path.splitext(x)[0] for x in files], columns=['ticker2'])
    
    df_not_converted = pd.merge(df_downloaded_tickers, df_converted_tickers, 
                      left_on='ticker1', 
                      right_on='ticker2', 
                      how='left', 
                      suffixes=('_left', '_right'))
    
    df = df_not_converted[df_not_converted['ticker2'].isna()]
    df = df.drop(columns=['ticker2'])
    df = df[~df['ticker1'].isin(tickers_to_skip)]
    
    return df

## Work with CSV files

In [488]:
def convert_files_json_to_csv(*args):
    for t in args:
        if t not in tickers_to_skip:
            convert_single_file_json_to_csv(t)

def convert_single_file_json_to_csv(ticker):
    # ticker = 'AMZN'
    json_path = f"{PATH}/downloaded/{ticker}.json"
    csv_path = f"{PATH}/converted/{ticker}.csv"
    try:
        df = pd.read_json(json_path)
        if len(df) > 0:
            print (f'Converting json for {ticker} to csv')
            df['date'] = df['series'].apply(lambda x: datetime.fromtimestamp(int(x['time'])))
            df['close'] = df['series'].apply(lambda x: x['close'])
            df['date'] = df["date"].dt.normalize()
            df = df[['date','close']]
            # df = df.sort_values("date").drop_duplicates("date", keep="last")
            df['date'] = df['date'].dt.strftime('%Y-%m-%d')
            # df['date2'] = pd.DatetimeIndex(['date'])
            df = df.set_index(pd.to_datetime(df['date']))
            df.to_csv(csv_path, index=False)
            return df
    except:
        print (f"Error in 'def convert_single_file_json_to_csv' converting {ticker} to csv")


def get_df_from_csv(ticker):
    
    # Try to get the file and if it doesn't exist issue a warning
    try:
        df = pd.read_csv(PATH + 'converted/' + ticker + '.csv')
        # df['date2'] = pd.DatetimeIndex(['date'])
        df = df.set_index(pd.to_datetime(df['date']))
        df.drop(columns=['date'], inplace=True)
        df = df.loc[S_DATE_STR:E_DATE_STR]
        
        # df = delete_unnamed_cols(df)
        
    except FileNotFoundError:
        missing_tickers.append(ticker)
        print(f"File for ticker {ticker} doesn't exist")
        return None
    else:
        return df

def get_wilshire_tickers():
    df_wilshire_tickers = pd.read_csv(PATH + '/Wilshire-5000-Stocks-New.csv')
    df_wilshire_tickers = df_wilshire_tickers.rename(columns={'Ticker':'ticker'}).drop(columns=['Company']).drop_duplicates()
    return df_wilshire_tickers

def get_column_from_csv(file, col_name):
    try:
        df = pd.read_csv(file)
    except FileNotFoundError:
        print ('File doesnt exist')
    else:
        return df[col_name]

## Add daily returns to CSV after converting to CSV

In [428]:
  

# def merge_df_by_column_name(col_name, sdate, edate, *tickers):
#     mult_df = pd.DataFrame()
#     for x in tickers:
#         df = get_df_from_csv(x)
#         mask = (df.index >= sdate) & (df.index <= edate)
#         mult_df[x] = df.loc[mask][col_name]

#     return mult_df

def plot_return_mult_stocks(investment, stock_df):
    (stock_df / stock_df.iloc[0] * investment).plot(figsize = (15,6))
    plt.show()

def merge_df_by_column_name(col_name, sdate, edate, *tickers):
    mult_df = pd.DataFrame()
    for x in tickers:
        df = get_df_from_csv(x)
        # df['Date'] = pd.to_datetime(df['date'])
        # mask = (df['Date'] >= sdate) & (df['Date'] <= edate)
        mult_df[x] = df.loc[sdate:edate][col_name]

    return mult_df

## Add daily returns to converted CSV file

In [243]:
def add_daily_returns_to_stocks(*args):
    for t in args:
        if t not in tickers_to_skip:
            add_daily_returns(t)
    
def add_daily_returns(ticker):
    
    print(f"Adding daily returns to {ticker}")

    try:
        # Get a dataframe for that ticker
        stock_df = get_df_from_csv(ticker)
        
        # # Add daily return to this dataframe
        if stock_df is not None:
            
            stock_df['daily_return'] = (stock_df['close'] / stock_df['close'].shift(1)) - 1
            stock_df.to_csv(PATH + 'converted/' + ticker + '.csv')
            
    except Exception as e: 
        print (f"Error in 'def add_daily_returns' ticker: {ticker} ------------------")
        print (e)

In [480]:
def get_return_defined_time(df, syear, smonth, sday, eyear, emonth, eday):
    # Create string representations for the dates
    start = f"{syear}-{smonth}-{sday}"
    end = f"{eyear}-{emonth}-{eday}"
    
    # Use a mask to grab data between defined dates
    mask = (df.index >= start) & (df.index <= end)
    
    # Get the mean of the column named daily return
    daily_ret = df.loc[mask]['daily_return'].mean()
    
    # Get the number of days between 2 dates
    df2 = df.loc[mask]
    days = df2.shape[0]

    # Return the total return between 2 dates
    return (days * daily_ret)

def get_roi_defined_time(df):
    # Set as a datetime
    # df['date'] = pd.to_datetime(df['date'])
    start_val = df.loc[S_DATE_STR:S_DATE_STR, 'close'].iloc[0]
    print("Initial Price :", start_val)
    
    # ----- I CHANGED THIS AFTER THE VIDEO -----
    
    end_val = df.loc[E_DATE_STR:E_DATE_STR, 'close'].iloc[0]
    print(end_val.item())
    print("Final Price :", end_val.item())
    
    # ----- END OF VIDEO CHANGES -----
    
    # Calculate return on investment
    roi = (end_val - start_val) / start_val

    # Return the total return between 2 dates
    return roi

In [403]:
    
def get_stock_mean_and_sd(stock_df, ticker):
    return stock_df[ticker].mean(), stock_df[ticker].std()

# Receives the dataframe with the stock ticker as the column name and
# the Adj Close values as the column data and returns the mean and 
# standard deviation
def get_mult_stock_mean_sd(stock_df):
    for stock in stock_df:
        mean, sd = get_stock_mean_and_sd(stock_df, stock)
        coeff_of_var = sd / mean
        print("Stock: {:10} Mean: {:7.2f} Standard deviation: {:2.2f}".format(stock, mean, sd))
        print("Coefficient of Variation: {}\n".format(coeff_of_var))

# Receives the dataframe with the Adj Close data and returns the coefficient of variation
def get_cov(stock_df):
    mean = stock_df['close'].mean()
    sd = stock_df['close'].std()
    cov = sd / mean
    return cov

# Receives a start and end date and returns the 1st date in that range
def get_valid_dates(df, sdate, edate):
    
    try:
        # mask = (df['date'] > sdate) & (df['date'] <= edate) 
        sm_df = df.loc[sdate:edate]
        if not sm_df.empty:
            sm_date = str(sm_df.index.min()).split(' ')[0]
            last_date = str(sm_df.index.max()).split(' ')[0]
            
            date_leading = str(sm_df.index.min()).split(' ')[0] #'-'.join(('0' if len(x) < 2 else '')+x for x in sm_date.split('-'))
            date_ending = str(sm_df.index.max()).split(' ')[0]  #'-'.join(('0' if len(x) < 2 else '')+x for x in last_date.split('-'))
            # print(date_leading, " ", date_ending)
        else:
            return None, None
    except Exception:
        print("Date Corrupted")
    else:
        return date_leading, date_ending


def roi_between_dates(df, sdate, edate):
    try: 
        start_val = df.loc[sdate,'close'] 
        end_val = df.loc[edate,'close']
        roi = ((end_val - start_val) / start_val)
    except Exception:
        print("Data Corrupted")
    else:
        return roi

def get_mean_between_dates(df, sdate, edate):
    mask = (df.index > sdate) & (df.index <= edate)    
    return df[mask]['close'].mean()

def get_sd_between_dates(df, sdate, edate):
    # mask = (df['Date'] > sdate) & (df['Date'] <= edate)
    mask = (df.index > sdate) & (df.index <= edate)
    return df[mask]["close"].std()

# get coeff of var
def get_cov_between_dates(df, sdate, edate):
    mean = get_mean_between_dates(df, sdate, edate)
    sd = get_sd_between_dates(df, sdate, edate)
    return sd / mean

def get_cov_ror(tickers, sdate, edate):
    # Define column names for dataframe
    col_names = ["Ticker", "COV", "ROI"]
    
    # Create dataframe with column names
    df = pd.DataFrame(columns = col_names)
    
    for ticker in tickers:
        s_df = get_df_from_csv(ticker)
    
        sdate2, edate2 = get_valid_dates(s_df, sdate, edate)
    
        cov = get_cov_between_dates(s_df, sdate2, edate2)
    
        # Set date as index
        # s_df = s_df.set_index(['Date'])
        roi = roi_between_dates(s_df, sdate2, edate2)

        # Add stock data to new dataframe row
        # len provides the length of the dataframe which is the next open index
        df.loc[len(df.index)] = [ticker, cov, roi]
    
    return df

# Merge Multiple Stocks in One Dataframe by Column Name

In [481]:
tickers_to_skip = ['FIT']
download_tickers(3)
arr = get_tickers_not_converted()['ticker1'].to_numpy()
arr

convert_files_json_to_csv(*arr)
add_daily_returns_to_stocks(*arr)

File for AAL already exists!
File for AME already exists!
File for BA already exists!
File for CHRW already exists!
File for CARR already exists!
File for CAT already exists!
File for CTAS already exists!
File for CPRT already exists!
File for CSX already exists!
File for CMI already exists!
File for DE already exists!
File for DAL already exists!
File for DOV already exists!
File for ETN already exists!
File for EMR already exists!
File for EFX already exists!
File for EXPD already exists!
File for FAST already exists!
File for FDX already exists!
File for FTV already exists!
File for FBHS already exists!
File for GNRC already exists!
File for GD already exists!
File for GE already exists!
File for HON already exists!
File for HWM already exists!
File for HII already exists!
File for IEX already exists!
File for INFO already exists!
File for ITW already exists!
File for IR already exists!
File for JBHT already exists!
File for J already exists!
File for JCI already exists!
File for KSU already exists!
File for LHX already exists!
File for LDOS already exists!
File for LMT already exists!
File for MAS already exists!
File for NLSN already exists!
File for NSC already exists!
File for NOC already exists!
File for ODFL already exists!
File for OTIS already exists!
File for PCAR already exists!
File for PH already exists!
File for PNR already exists!
File for PWR already exists!
File for RTX already exists!
File for RSG already exists!
File for RHI already exists!
File for ROK already exists!
File for ROL already exists!
File for ROP already exists!
File for SNA already exists!
File for LUV already exists!
File for SWK already exists!
File for TDY already exists!
File for TXT already exists!
File for TT already exists!
File for TDG already exists!
File for UNP already exists!
File for UAL already exists!
File for UPS already exists!
File for URI already exists!
File for VRSK already exists!
File for GWW already exists!
File for WAB already exists!
File for WM already exists!
File for XYL already exists!
DONE DOWNLOADING!

## Correlation

In [449]:

   
        
stock_a = get_df_from_csv('AMZN')
stock_a

sdate, edate = get_valid_dates(stock_a, '2020-01-01','2020-12-31')
print (sdate, edate)
print ('mean:' , get_mean_between_dates(stock_a, sdate, edate))
print ('sd:' , get_sd_between_dates(stock_a, sdate, edate))
print ('cov:' , get_cov_between_dates(stock_a, sdate, edate))

print ('roi ', roi_between_dates(stock_a, sdate, edate))

files = [x for x in listdir(PATH + 'converted/') if isfile(join(PATH, 'converted/', x))]
tickers = [os.path.splitext(x)[0] for x in files]
tickers.sort()
tickers

# Remove CRC GRUB AAN ARNC
market_df = get_cov_ror(tickers, '2020-01-03', '2020-12-31')
# market_df.sort_values(by=['ROI'], ascending=False)

# get_cov_ror

# df = merge_df_by_column_name('close', '2020-01-01','2020-12-31', * ["META", "AMZN", "AAPL", "NFLX", "GOOG"])
# df

# roi = get_roi_defined_time(stock_df)
# print ("ROI:", roi)

# stock_df.loc[S_DATE_STR:S_DATE_STR, 'close'].iloc[0]
    

# # d = stock_df.loc['2020-01-01':'2020-1-10']
# # d
# plot_return_mult_stocks(100, df)

# # get_return_defined_time (stock_df, 2020, 1, 1, 2020, 12, 31)

# get_mult_stock_mean_sd(df)

# s,e = get_valid_dates(stock_df, S_DATE_DATETIME, E_DATE_STR)
# roi_between_dates(stock_df, S_DATE_STR, E_DATE_STR)


# get_cov_between_dates(stock_df, S_DATE_STR, E_DATE_STR)

# Correlation tells us how closely 2 stocks returns move together
# Correlation is a standardized value lying between -1 and 1
# When this value is greater that .5 we say that these stocks are strongly correlated
# Of course each stocks price is perfectly correlated with itself

# We focus on the correlation of returns because investors care about returns 

faang_list = ["META", "AMZN", "AAPL", "NFLX", "GOOG"]
mult_df = merge_df_by_column_name('daily_return',  '2020-1-1', '2020-12-31', *faang_list)
mult_df

# # We can look at the correlation between Netflix and the others


# # We can plot this in a bar chart
# mult_df.corr()['NFLX'].plot(kind='bar')
# plt.show()

2020-01-02 2020-12-31
mean: 134.19808134920635
sd: 27.230060677719393
cov: 0.20290946341372884
roi  0.7159709379824132

          META      AMZN      AAPL      NFLX      GOOG
META  1.000000  0.682311  0.767307  0.574569  0.803420
AMZN  0.682311  1.000000  0.697746  0.678707  0.680991
AAPL  0.767307  0.697746  1.000000  0.559469  0.752260
NFLX  0.574569  0.678707  0.559469  1.000000  0.529425
GOOG  0.803420  0.680991  0.752260  0.529425  1.000000

## Variance

In [451]:


faang_list = ["META", "AMZN", "AAPL", "NFLX", "GOOG", "ADP"]
mult_df = merge_df_by_column_name('daily_return',  '2020-1-1', '2020-12-31', *faang_list)
# mult_df

# Generate a Correlation Matrix
# mult_df.corr()

# mult_df.corr()['NFLX']

# Remember variance is a measure of how spread out a data set is
# Get Netflix variance
# mult_df['NFLX'].var()

# Annualize by getting the number of samples and multiply
days = len(mult_df.index) # 253
nflx_a_var = mult_df['ADP'].var() * days
nflx_a_var

0.20156559749012817

## Covariance
##### Covariance is the measure of the relationship between 2 blocks of data. The covariance of a stock to itself is the variance of that variable.

In [448]:
mult_df.cov() * 253

          META      AMZN      AAPL      NFLX      GOOG       ADP
META  0.211498  0.121090  0.164972  0.122336  0.141870  0.116945
AMZN  0.121090  0.148918  0.125881  0.121259  0.100904  0.069677
AAPL  0.164972  0.125881  0.218563  0.121094  0.135036  0.133399
NFLX  0.122336  0.121259  0.121094  0.214347  0.094115  0.074997
GOOG  0.141870  0.100904  0.135036  0.094115  0.147431  0.116990
ADP   0.116945  0.069677  0.133399  0.074997  0.116990  0.201566

In [450]:
mult_df.corr()

          META      AMZN      AAPL      NFLX      GOOG
META  1.000000  0.682311  0.767307  0.574569  0.803420
AMZN  0.682311  1.000000  0.697746  0.678707  0.680991
AAPL  0.767307  0.697746  1.000000  0.559469  0.752260
NFLX  0.574569  0.678707  0.559469  1.000000  0.529425
GOOG  0.803420  0.680991  0.752260  0.529425  1.000000

## Calculating a Portfolios Variance
###### When calculating the variance of a portfolio we must define its weight, or how much of the portfolio it makes up. If you add up the weight of all stocks you get a value of 1.

###### w_1, w_2 = Stock Weights 

###### w_1, w_2 = Stock Standard Deviations

###### Portfolio Variance = (w_1*sigma_1 + w_2*sigma_2)^2

###### Since 

###### Then the Portfolio Variance = w_1^2*sigma_1^2 + 2w_1*sigma_1w_2*sigma_2*rho_12 + w_2^2*sigma_2^2

In [459]:
port_list = ['META', 'NEM']
port_df = merge_df_by_column_name('daily_return', '2020-01-01','2020-12-31', *port_list)

# port_df.corr()

price_df = merge_df_by_column_name('close', '2020-01-01','2020-12-31', *port_list)
price_df.head()

fb_price = 208.14
nm_price = 36.19
port_value = fb_price + (nm_price * 5)

fb_wt = fb_price / port_value
nm_wt = (nm_price * 5) / port_value

wts = np.array([fb_wt, nm_wt])
port_var = np.dot(wts.T, np.dot(port_df.cov() * 253, wts))
print ("Port Var: ", port_var)
print ("FB var : ", port_df['META'].var() * 253)
print ("NEM var : ", port_df['NEM'].var() * 253)

Port Var:  0.12778622570355963
FB var :  0.2114976949437114
NEM var :  0.2133476369891

## Sectors

In [474]:
sec_df = pd.read_csv(PATH + 'stock_sectors.csv')

# Get Industrials DF
indus_df = sec_df.loc[sec_df['Sector'] == "Industrials"]
health_df = sec_df.loc[sec_df['Sector'] == "Health Care"]
it_df = sec_df.loc[sec_df['Sector'] == "Information Technology"]
comm_df = sec_df.loc[sec_df['Sector'] == "Communication Services"]
staple_df = sec_df.loc[sec_df['Sector'] == "Consumer Staples"]
discretion_df = sec_df.loc[sec_df['Sector'] == "Consumer Discretionary"]
utility_df = sec_df.loc[sec_df['Sector'] == "Utilities"]
financial_df = sec_df.loc[sec_df['Sector'] == "Financials"]
material_df = sec_df.loc[sec_df['Sector'] == "Materials"]
restate_df = sec_df.loc[sec_df['Sector'] == "Real Estate"]
energy_df = sec_df.loc[sec_df['Sector'] == "Energy"]
sec_df

    Symbol                 Name                  Sector
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4     ABMD              Abiomed             Health Care
..     ...                  ...                     ...
500    YUM          Yum! Brands  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [489]:

def get_rois_for_stocks(stock_df):

    tickers = []
    rois = []

    for index, row in stock_df.iterrows():
        df = get_df_from_csv(row['Symbol'])
        if df is None:
            pass
        else:
            mask = (df.index > '2018-01-01') & (df.index <= '2020-12-31')
            
            if len(df.loc[mask]) > 0:
                tickers.append(row['Symbol'])
                sdate, edate = get_valid_dates(df, '2018-01-01', '2020-12-31')
                roi = roi_between_dates(df, sdate, edate)
                rois.append(roi)
    
    return pd.DataFrame({'Ticker' : tickers, 'ROI' : rois})
    
symbols = indus_df['Symbol'].to_numpy()
industrial = get_rois_for_stocks(indus_df)
health_care = get_rois_for_stocks(health_df)
it = get_rois_for_stocks(it_df)
commun = get_rois_for_stocks(comm_df)
staple = get_rois_for_stocks(staple_df)
discretion = get_rois_for_stocks(discretion_df)
utility = get_rois_for_stocks(utility_df)
finance = get_rois_for_stocks(financial_df)
material = get_rois_for_stocks(material_df)
restate = get_rois_for_stocks(restate_df)
energy = get_rois_for_stocks(energy_df)
missing_tickers

File for ticker FBHS doesn't exist
File for ticker KSU doesn't exist
File for ticker NLSN doesn't exist
File for ticker ABMD doesn't exist
File for ticker ALGN doesn't exist
File for ticker ABC doesn't exist
File for ticker AMGN doesn't exist
File for ticker ANTM doesn't exist
File for ticker BAX doesn't exist
File for ticker BDX doesn't exist
File for ticker BIO doesn't exist
File for ticker TECH doesn't exist
File for ticker BIIB doesn't exist
File for ticker BSX doesn't exist
File for ticker BMY doesn't exist
File for ticker CAH doesn't exist
File for ticker CTLT doesn't exist
File for ticker CNC doesn't exist
File for ticker CERN doesn't exist
File for ticker CRL doesn't exist
File for ticker CI doesn't exist
File for ticker CVS doesn't exist
File for ticker DHR doesn't exist
File for ticker DVA doesn't exist
File for ticker XRAY doesn't exist
File for ticker DXCM doesn't exist
File for ticker EW doesn't exist
File for ticker LLY doesn't exist
File for ticker GILD doesn't exist
File for ticker HCA doesn't exist
File for ticker HSIC doesn't exist
File for ticker HOLX doesn't exist
File for ticker HUM doesn't exist
File for ticker IDXX doesn't exist
File for ticker ILMN doesn't exist
File for ticker INCY doesn't exist
File for ticker ISRG doesn't exist
File for ticker IQV doesn't exist
File for ticker JNJ doesn't exist
File for ticker LH doesn't exist
File for ticker MCK doesn't exist
File for ticker MDT doesn't exist
File for ticker MRK doesn't exist
File for ticker MTD doesn't exist
File for ticker MRNA doesn't exist
File for ticker OGN doesn't exist
File for ticker PKI doesn't exist
File for ticker PRGO doesn't exist
File for ticker PFE doesn't exist
File for ticker DGX doesn't exist
File for ticker REGN doesn't exist
File for ticker RMD doesn't exist
File for ticker STE doesn't exist
File for ticker SYK doesn't exist
File for ticker TFX doesn't exist
File for ticker COO doesn't exist
File for ticker TMO doesn't exist
File for ticker UNH doesn't exist
File for ticker UHS doesn't exist
File for ticker VRTX doesn't exist
File for ticker VTRS doesn't exist
File for ticker WAT doesn't exist
File for ticker WST doesn't exist
File for ticker ZBH doesn't exist
File for ticker ZTS doesn't exist
File for ticker ACN doesn't exist
File for ticker ADBE doesn't exist
File for ticker AMD doesn't exist
File for ticker AKAM doesn't exist
File for ticker APH doesn't exist
File for ticker ADI doesn't exist
File for ticker ANSS doesn't exist
File for ticker AMAT doesn't exist
File for ticker ANET doesn't exist
File for ticker ADSK doesn't exist
File for ticker AVGO doesn't exist
File for ticker BR doesn't exist
File for ticker CDNS doesn't exist
File for ticker CDW doesn't exist
File for ticker CTXS doesn't exist
File for ticker CTSH doesn't exist
File for ticker GLW doesn't exist
File for ticker DXC doesn't exist
File for ticker ENPH doesn't exist
File for ticker FFIV doesn't exist
File for ticker FIS doesn't exist
File for ticker FISV doesn't exist
File for ticker FLT doesn't exist
File for ticker FTNT doesn't exist
File for ticker IT doesn't exist
File for ticker GPN doesn't exist
File for ticker HPE doesn't exist
File for ticker HPQ doesn't exist
File for ticker IBM doesn't exist
File for ticker INTC doesn't exist
File for ticker INTU doesn't exist
File for ticker IPGP doesn't exist
File for ticker JKHY doesn't exist
File for ticker JNPR doesn't exist
File for ticker KEYS doesn't exist
File for ticker KLAC doesn't exist
File for ticker LRCX doesn't exist
File for ticker MA doesn't exist
File for ticker MCHP doesn't exist
File for ticker MU doesn't exist
File for ticker MSFT doesn't exist
File for ticker MPWR doesn't exist
File for ticker MSI doesn't exist
File for ticker NTAP doesn't exist
File for ticker NLOK doesn't exist
File for ticker NVDA doesn't exist
File for ticker NXPI doesn't exist
File for ticker ORCL doesn't exist
File for ticker PAYX doesn't exist
File for ticker PAYC doesn't exist
File for ticker PYPL doesn't exist
File for ticker PTC doesn't exist
File for ticker QRVO doesn't exist
File for ticker QCOM doesn't exist
File for ticker CRM doesn't exist
File for ticker STX doesn't exist
File for ticker NOW doesn't exist
File for ticker SWKS doesn't exist
File for ticker SNPS doesn't exist
File for ticker TEL doesn't exist
File for ticker TER doesn't exist
File for ticker TXN doesn't exist
File for ticker TRMB doesn't exist
File for ticker TYL doesn't exist
File for ticker VRSN doesn't exist
File for ticker V doesn't exist
File for ticker WDC doesn't exist
File for ticker WU doesn't exist
File for ticker XLNX doesn't exist
File for ticker ZBRA doesn't exist
File for ticker ATVI doesn't exist
File for ticker GOOGL doesn't exist
File for ticker T doesn't exist
File for ticker CHTR doesn't exist
File for ticker CMCSA doesn't exist
File for ticker DISCA doesn't exist
File for ticker DISCK doesn't exist
File for ticker DISH doesn't exist
File for ticker EA doesn't exist
File for ticker FB doesn't exist
File for ticker FOXA doesn't exist
File for ticker FOX doesn't exist
File for ticker IPG doesn't exist
File for ticker LYV doesn't exist
File for ticker LUMN doesn't exist
File for ticker NWSA doesn't exist
File for ticker NWS doesn't exist
File for ticker OMC doesn't exist
File for ticker TMUS doesn't exist
File for ticker TTWO doesn't exist
File for ticker DIS doesn't exist
File for ticker TWTR doesn't exist
File for ticker VZ doesn't exist
File for ticker VIAC doesn't exist
File for ticker ADM doesn't exist
File for ticker MO doesn't exist
File for ticker BF.B doesn't exist
File for ticker CPB doesn't exist
File for ticker CHD doesn't exist
File for ticker CLX doesn't exist
File for ticker KO doesn't exist
File for ticker CL doesn't exist
File for ticker CAG doesn't exist
File for ticker STZ doesn't exist
File for ticker COST doesn't exist
File for ticker EL doesn't exist
File for ticker GIS doesn't exist
File for ticker HRL doesn't exist
File for ticker SJM doesn't exist
File for ticker K doesn't exist
File for ticker KMB doesn't exist
File for ticker KHC doesn't exist
File for ticker KR doesn't exist
File for ticker LW doesn't exist
File for ticker MKC doesn't exist
File for ticker TAP doesn't exist
File for ticker MDLZ doesn't exist
File for ticker MNST doesn't exist
File for ticker PEP doesn't exist
File for ticker PM doesn't exist
File for ticker PG doesn't exist
File for ticker SYY doesn't exist
File for ticker HSY doesn't exist
File for ticker TSN doesn't exist
File for ticker WBA doesn't exist
File for ticker WMT doesn't exist
File for ticker APTV doesn't exist
File for ticker AZO doesn't exist
File for ticker BBWI doesn't exist
File for ticker BBY doesn't exist
File for ticker BKNG doesn't exist
File for ticker BWA doesn't exist
File for ticker CZR doesn't exist
File for ticker KMX doesn't exist
File for ticker CCL doesn't exist
File for ticker CMG doesn't exist
File for ticker DHI doesn't exist
File for ticker DRI doesn't exist
File for ticker DG doesn't exist
File for ticker DLTR doesn't exist
File for ticker DPZ doesn't exist
File for ticker EBAY doesn't exist
File for ticker ETSY doesn't exist
File for ticker EXPE doesn't exist
File for ticker F doesn't exist
File for ticker GPS doesn't exist
File for ticker GRMN doesn't exist
File for ticker GM doesn't exist
File for ticker GPC doesn't exist
File for ticker HBI doesn't exist
File for ticker HAS doesn't exist
File for ticker HLT doesn't exist
File for ticker HD doesn't exist
File for ticker LVS doesn't exist
File for ticker LEG doesn't exist
File for ticker LEN doesn't exist
File for ticker LKQ doesn't exist
File for ticker LOW doesn't exist
File for ticker MAR doesn't exist
File for ticker MCD doesn't exist
File for ticker MGM doesn't exist
File for ticker MHK doesn't exist
File for ticker NWL doesn't exist
File for ticker NKE doesn't exist
File for ticker NCLH doesn't exist
File for ticker NVR doesn't exist
File for ticker ORLY doesn't exist
File for ticker PENN doesn't exist
File for ticker POOL doesn't exist
File for ticker PHM doesn't exist
File for ticker PVH doesn't exist
File for ticker RL doesn't exist
File for ticker ROST doesn't exist
File for ticker RCL doesn't exist
File for ticker SBUX doesn't exist
File for ticker TPR doesn't exist
File for ticker TGT doesn't exist
File for ticker TSLA doesn't exist
File for ticker TJX doesn't exist
File for ticker TSCO doesn't exist
File for ticker ULTA doesn't exist
File for ticker UAA doesn't exist
File for ticker UA doesn't exist
File for ticker VFC doesn't exist
File for ticker WHR doesn't exist
File for ticker WYNN doesn't exist
File for ticker YUM doesn't exist
File for ticker AES doesn't exist
File for ticker LNT doesn't exist
File for ticker AEE doesn't exist
File for ticker AEP doesn't exist
File for ticker AWK doesn't exist
File for ticker ATO doesn't exist
File for ticker CNP doesn't exist
File for ticker CMS doesn't exist
File for ticker ED doesn't exist
File for ticker D doesn't exist
File for ticker DTE doesn't exist
File for ticker DUK doesn't exist
File for ticker EIX doesn't exist
File for ticker ETR doesn't exist
File for ticker EVRG doesn't exist
File for ticker ES doesn't exist
File for ticker EXC doesn't exist
File for ticker FE doesn't exist
File for ticker NEE doesn't exist
File for ticker NI doesn't exist
File for ticker NRG doesn't exist
File for ticker PNW doesn't exist
File for ticker PPL doesn't exist
File for ticker PEG doesn't exist
File for ticker SRE doesn't exist
File for ticker SO doesn't exist
File for ticker WEC doesn't exist
File for ticker XEL doesn't exist
File for ticker AFL doesn't exist
File for ticker ALL doesn't exist
File for ticker AXP doesn't exist
File for ticker AIG doesn't exist
File for ticker AMP doesn't exist
File for ticker AON doesn't exist
File for ticker AJG doesn't exist
File for ticker AIZ doesn't exist
File for ticker BAC doesn't exist
File for ticker BRK.B doesn't exist
File for ticker BLK doesn't exist
File for ticker BK doesn't exist
File for ticker COF doesn't exist
File for ticker CBOE doesn't exist
File for ticker SCHW doesn't exist
File for ticker CB doesn't exist
File for ticker CINF doesn't exist
File for ticker C doesn't exist
File for ticker CFG doesn't exist
File for ticker CME doesn't exist
File for ticker CMA doesn't exist
File for ticker DFS doesn't exist
File for ticker RE doesn't exist
File for ticker FITB doesn't exist
File for ticker FRC doesn't exist
File for ticker BEN doesn't exist
File for ticker GL doesn't exist
File for ticker GS doesn't exist
File for ticker HBAN doesn't exist
File for ticker ICE doesn't exist
File for ticker IVZ doesn't exist
File for ticker JPM doesn't exist
File for ticker KEY doesn't exist
File for ticker LNC doesn't exist
File for ticker L doesn't exist
File for ticker MTB doesn't exist
File for ticker MKTX doesn't exist
File for ticker MMC doesn't exist
File for ticker MET doesn't exist
File for ticker MCO doesn't exist
File for ticker MS doesn't exist
File for ticker MSCI doesn't exist
File for ticker NDAQ doesn't exist
File for ticker NTRS doesn't exist
File for ticker PBCT doesn't exist
File for ticker PNC doesn't exist
File for ticker PFG doesn't exist
File for ticker PGR doesn't exist
File for ticker PRU doesn't exist
File for ticker RJF doesn't exist
File for ticker RF doesn't exist
File for ticker SPGI doesn't exist
File for ticker STT doesn't exist
File for ticker SIVB doesn't exist
File for ticker SYF doesn't exist
File for ticker TROW doesn't exist
File for ticker HIG doesn't exist
File for ticker TRV doesn't exist
File for ticker TFC doesn't exist
File for ticker USB doesn't exist
File for ticker UNM doesn't exist
File for ticker WRB doesn't exist
File for ticker WFC doesn't exist
File for ticker WLTW doesn't exist
File for ticker ZION doesn't exist
File for ticker APD doesn't exist
File for ticker ALB doesn't exist
File for ticker AMCR doesn't exist
File for ticker AVY doesn't exist
File for ticker BLL doesn't exist
File for ticker CE doesn't exist
File for ticker CF doesn't exist
File for ticker CTVA doesn't exist
File for ticker DOW doesn't exist
File for ticker DD doesn't exist
File for ticker EMN doesn't exist
File for ticker ECL doesn't exist
File for ticker FMC doesn't exist
File for ticker FCX doesn't exist
File for ticker IFF doesn't exist
File for ticker IP doesn't exist
File for ticker LIN doesn't exist
File for ticker LYB doesn't exist
File for ticker MLM doesn't exist
File for ticker NUE doesn't exist
File for ticker PKG doesn't exist
File for ticker PPG doesn't exist
File for ticker SEE doesn't exist
File for ticker SHW doesn't exist
File for ticker MOS doesn't exist
File for ticker VMC doesn't exist
File for ticker WRK doesn't exist
File for ticker ARE doesn't exist
File for ticker AMT doesn't exist
File for ticker AVB doesn't exist
File for ticker BXP doesn't exist
File for ticker CBRE doesn't exist
File for ticker CCI doesn't exist
File for ticker DLR doesn't exist
File for ticker DRE doesn't exist
File for ticker EQIX doesn't exist
File for ticker EQR doesn't exist
File for ticker ESS doesn't exist
File for ticker EXR doesn't exist
File for ticker FRT doesn't exist
File for ticker PEAK doesn't exist
File for ticker HST doesn't exist
File for ticker IRM doesn't exist
File for ticker KIM doesn't exist
File for ticker MAA doesn't exist
File for ticker PLD doesn't exist
File for ticker PSA doesn't exist
File for ticker O doesn't exist
File for ticker REG doesn't exist
File for ticker SBAC doesn't exist
File for ticker SPG doesn't exist
File for ticker UDR doesn't exist
File for ticker VTR doesn't exist
File for ticker VNO doesn't exist
File for ticker WELL doesn't exist
File for ticker WY doesn't exist
File for ticker APA doesn't exist
File for ticker BKR doesn't exist
File for ticker COG doesn't exist
File for ticker CVX doesn't exist
File for ticker COP doesn't exist
File for ticker DVN doesn't exist
File for ticker FANG doesn't exist
File for ticker EOG doesn't exist
File for ticker XOM doesn't exist
File for ticker HAL doesn't exist
File for ticker HES doesn't exist
File for ticker KMI doesn't exist
File for ticker MRO doesn't exist
File for ticker MPC doesn't exist
File for ticker NOV doesn't exist
File for ticker OXY doesn't exist
File for ticker OKE doesn't exist
File for ticker PSX doesn't exist
File for ticker PXD doesn't exist
File for ticker SLB doesn't exist
File for ticker VLO doesn't exist
File for ticker WMB doesn't exist

['FBHS',
 'KSU',
 'NLSN',
 'ABMD',
 'ALGN',
 'ABC',
 'AMGN',
 'ANTM',
 'BAX',
 'BDX',
 'BIO',
 'TECH',
 'BIIB',
 'BSX',
 'BMY',
 'CAH',
 'CTLT',
 'CNC',
 'CERN',
 'CRL',
 'CI',
 'CVS',
 'DHR',
 'DVA',
 'XRAY',
 'DXCM',
 'EW',
 'LLY',
 'GILD',
 'HCA',
 'HSIC',
 'HOLX',
 'HUM',
 'IDXX',
 'ILMN',
 'INCY',
 'ISRG',
 'IQV',
 'JNJ',
 'LH',
 'MCK',
 'MDT',
 'MRK',
 'MTD',
 'MRNA',
 'OGN',
 'PKI',
 'PRGO',
 'PFE',
 'DGX',
 'REGN',
 'RMD',
 'STE',
 'SYK',
 'TFX',
 'COO',
 'TMO',
 'UNH',
 'UHS',
 'VRTX',
 'VTRS',
 'WAT',
 'WST',
 'ZBH',
 'ZTS',
 'ACN',
 'ADBE',
 'AMD',
 'AKAM',
 'APH',
 'ADI',
 'ANSS',
 'AMAT',
 'ANET',
 'ADSK',
 'AVGO',
 'BR',
 'CDNS',
 'CDW',
 'CTXS',
 'CTSH',
 'GLW',
 'DXC',
 'ENPH',
 'FFIV',
 'FIS',
 'FISV',
 'FLT',
 'FTNT',
 'IT',
 'GPN',
 'HPE',
 'HPQ',
 'IBM',
 'INTC',
 'INTU',
 'IPGP',
 'JKHY',
 'JNPR',
 'KEYS',
 'KLAC',
 'LRCX',
 'MA',
 'MCHP',
 'MU',
 'MSFT',
 'MPWR',
 'MSI',
 'NTAP',
 'NLOK',
 'NVDA',
 'NXPI',
 'ORCL',
 'PAYX',
 'PAYC',
 'PYPL',
 'PTC',
 'QRVO',
 'QCOM',
 'CRM',
 'STX',
 'NOW',
 'SWKS',
 'SNPS',
 'TEL',
 'TER',
 'TXN',
 'TRMB',
 'TYL',
 'VRSN',
 'V',
 'WDC',
 'WU',
 'XLNX',
 'ZBRA',
 'ATVI',
 'GOOGL',
 'T',
 'CHTR',
 'CMCSA',
 'DISCA',
 'DISCK',
 'DISH',
 'EA',
 'FB',
 'FOXA',
 'FOX',
 'IPG',
 'LYV',
 'LUMN',
 'NWSA',
 'NWS',
 'OMC',
 'TMUS',
 'TTWO',
 'DIS',
 'TWTR',
 'VZ',
 'VIAC',
 'ADM',
 'MO',
 'BF.B',
 'CPB',
 'CHD',
 'CLX',
 'KO',
 'CL',
 'CAG',
 'STZ',
 'COST',
 'EL',
 'GIS',
 'HRL',
 'SJM',
 'K',
 'KMB',
 'KHC',
 'KR',
 'LW',
 'MKC',
 'TAP',
 'MDLZ',
 'MNST',
 'PEP',
 'PM',
 'PG',
 'SYY',
 'HSY',
 'TSN',
 'WBA',
 'WMT',
 'APTV',
 'AZO',
 'BBWI',
 'BBY',
 'BKNG',
 'BWA',
 'CZR',
 'KMX',
 'CCL',
 'CMG',
 'DHI',
 'DRI',
 'DG',
 'DLTR',
 'DPZ',
 'EBAY',
 'ETSY',
 'EXPE',
 'F',
 'GPS',
 'GRMN',
 'GM',
 'GPC',
 'HBI',
 'HAS',
 'HLT',
 'HD',
 'LVS',
 'LEG',
 'LEN',
 'LKQ',
 'LOW',
 'MAR',
 'MCD',
 'MGM',
 'MHK',
 'NWL',
 'NKE',
 'NCLH',
 'NVR',
 'ORLY',
 'PENN',
 'POOL',
 'PHM',
 'PVH',
 'RL',
 'ROST',
 'RCL',
 'SBUX',
 'TPR',
 'TGT',
 'TSLA',
 'TJX',
 'TSCO',
 'ULTA',
 'UAA',
 'UA',
 'VFC',
 'WHR',
 'WYNN',
 'YUM',
 'AES',
 'LNT',
 'AEE',
 'AEP',
 'AWK',
 'ATO',
 'CNP',
 'CMS',
 'ED',
 'D',
 'DTE',
 'DUK',
 'EIX',
 'ETR',
 'EVRG',
 'ES',
 'EXC',
 'FE',
 'NEE',
 'NI',
 'NRG',
 'PNW',
 'PPL',
 'PEG',
 'SRE',
 'SO',
 'WEC',
 'XEL',
 'AFL',
 'ALL',
 'AXP',
 'AIG',
 'AMP',
 'AON',
 'AJG',
 'AIZ',
 'BAC',
 'BRK.B',
 'BLK',
 'BK',
 'COF',
 'CBOE',
 'SCHW',
 'CB',
 'CINF',
 'C',
 'CFG',
 'CME',
 'CMA',
 'DFS',
 'RE',
 'FITB',
 'FRC',
 'BEN',
 'GL',
 'GS',
 'HBAN',
 'ICE',
 'IVZ',
 'JPM',
 'KEY',
 'LNC',
 'L',
 'MTB',
 'MKTX',
 'MMC',
 'MET',
 'MCO',
 'MS',
 'MSCI',
 'NDAQ',
 'NTRS',
 'PBCT',
 'PNC',
 'PFG',
 'PGR',
 'PRU',
 'RJF',
 'RF',
 'SPGI',
 'STT',
 'SIVB',
 'SYF',
 'TROW',
 'HIG',
 'TRV',
 'TFC',
 'USB',
 'UNM',
 'WRB',
 'WFC',
 'WLTW',
 'ZION',
 'APD',
 'ALB',
 'AMCR',
 'AVY',
 'BLL',
 'CE',
 'CF',
 'CTVA',
 'DOW',
 'DD',
 'EMN',
 'ECL',
 'FMC',
 'FCX',
 'IFF',
 'IP',
 'LIN',
 'LYB',
 'MLM',
 'NUE',
 'PKG',
 'PPG',
 'SEE',
 'SHW',
 'MOS',
 'VMC',
 'WRK',
 'ARE',
 'AMT',
 'AVB',
 'BXP',
 'CBRE',
 'CCI',
 'DLR',
 'DRE',
 'EQIX',
 'EQR',
 'ESS',
 'EXR',
 'FRT',
 'PEAK',
 'HST',
 'IRM',
 'KIM',
 'MAA',
 'PLD',
 'PSA',
 'O',
 'REG',
 'SBAC',
 'SPG',
 'UDR',
 'VTR',
 'VNO',
 'WELL',
 'WY',
 'APA',
 'BKR',
 'COG',
 'CVX',
 'COP',
 'DVN',
 'FANG',
 'EOG',
 'XOM',
 'HAL',
 'HES',
 'KMI',
 'MRO',
 'MPC',
 'NOV',
 'OXY',
 'OKE',
 'PSX',
 'PXD',
 'SLB',
 'VLO',
 'WMB']